import dotenv from "dotenv";
dotenv.config();

import mongoose from "mongoose";
import VocabularyContent from "./src/models/vocabularyContent.js";

const MONGO_URI = process.env.MONGO_URI || process.env.MONGODB_URI;

const tasks = [
  // ─── BEGINNER ───────────────────────────────────────────
  {
    level: "beginner", order: 1, theme: "Daily Objects",
    title: "Everyday Objects Around You",
    description: "Learn common words for objects you see every day.",
    estimatedMinutes: 10,
    questions: [
      { word: "Chair", questionText: "What does 'chair' mean?", options: ["A thing you sleep on", "A thing you sit on", "A thing you eat from", "A thing you write on"], correctAnswer: "A thing you sit on" },
      { word: "Window", questionText: "What does 'window' mean?", options: ["A door to outside", "A glass opening in a wall", "A type of roof", "A wooden floor"], correctAnswer: "A glass opening in a wall" },
      { word: "Clock", questionText: "What does 'clock' mean?", options: ["A device that shows time", "A type of lamp", "A kitchen tool", "A writing tool"], correctAnswer: "A device that shows time" },
      { word: "Bag", questionText: "What does 'bag' mean?", options: ["A type of shoe", "A container you carry things in", "A piece of clothing", "A kitchen appliance"], correctAnswer: "A container you carry things in" },
      { word: "Mirror", questionText: "What does 'mirror' mean?", options: ["A type of window", "A surface that shows your reflection", "A painting on a wall", "A type of door"], correctAnswer: "A surface that shows your reflection" },
      { word: "Lamp", questionText: "What does 'lamp' mean?", options: ["A device that produces light", "A device that produces sound", "A type of chair", "A cooking tool"], correctAnswer: "A device that produces light" },
      { word: "Pillow", questionText: "What does 'pillow' mean?", options: ["A type of blanket", "A soft cushion for your head", "A type of mattress", "A wooden board"], correctAnswer: "A soft cushion for your head" },
      { word: "Shelf", questionText: "What does 'shelf' mean?", options: ["A flat surface fixed to a wall to put things on", "A type of drawer", "A large cupboard", "A type of table"], correctAnswer: "A flat surface fixed to a wall to put things on" },
      { word: "Curtain", questionText: "What does 'curtain' mean?", options: ["A type of carpet", "A cloth that covers a window", "A type of wallpaper", "A wooden door"], correctAnswer: "A cloth that covers a window" },
      { word: "Bucket", questionText: "What does 'bucket' mean?", options: ["A flat plate", "A round open container with a handle", "A type of bottle", "A cooking pan"], correctAnswer: "A round open container with a handle" },
    ],
  },
  {
    level: "beginner", order: 2, theme: "Food and Drinks",
    title: "Food and Drinks Vocabulary",
    description: "Learn words for common foods and drinks.",
    estimatedMinutes: 10,
    questions: [
      { word: "Bread", questionText: "What does 'bread' mean?", options: ["A baked food made from flour", "A type of vegetable", "A sweet dessert", "A hot drink"], correctAnswer: "A baked food made from flour" },
      { word: "Soup", questionText: "What does 'soup' mean?", options: ["A cold solid food", "A liquid food cooked with vegetables or meat", "A type of salad", "A sweet snack"], correctAnswer: "A liquid food cooked with vegetables or meat" },
      { word: "Juice", questionText: "What does 'juice' mean?", options: ["A hot drink made from leaves", "A liquid from fruits or vegetables", "A type of milk", "A carbonated drink"], correctAnswer: "A liquid from fruits or vegetables" },
      { word: "Rice", questionText: "What does 'rice' mean?", options: ["A type of bread", "Small white grains that are cooked and eaten", "A type of noodle", "A green vegetable"], correctAnswer: "Small white grains that are cooked and eaten" },
      { word: "Egg", questionText: "What does 'egg' mean?", options: ["A round fruit", "An oval food produced by birds", "A type of cheese", "A root vegetable"], correctAnswer: "An oval food produced by birds" },
      { word: "Butter", questionText: "What does 'butter' mean?", options: ["A type of oil", "A yellow fatty food made from cream", "A white powder", "A sweet syrup"], correctAnswer: "A yellow fatty food made from cream" },
      { word: "Sugar", questionText: "What does 'sugar' mean?", options: ["A salty white powder", "A sweet white substance used in food", "A type of flour", "A sour liquid"], correctAnswer: "A sweet white substance used in food" },
      { word: "Meat", questionText: "What does 'meat' mean?", options: ["The flesh of animals used as food", "A type of vegetable", "A dairy product", "A type of grain"], correctAnswer: "The flesh of animals used as food" },
      { word: "Snack", questionText: "What does 'snack' mean?", options: ["A large main meal", "A small amount of food eaten between meals", "A type of drink", "A cooking method"], correctAnswer: "A small amount of food eaten between meals" },
      { word: "Salad", questionText: "What does 'salad' mean?", options: ["A hot cooked dish", "A cold dish of raw vegetables", "A type of soup", "A sweet dessert"], correctAnswer: "A cold dish of raw vegetables" },
    ],
  },
  {
    level: "beginner", order: 3, theme: "Colors and Shapes",
    title: "Colors and Shapes",
    description: "Learn words to describe colors and shapes.",
    estimatedMinutes: 10,
    questions: [
      { word: "Scarlet", questionText: "What does 'scarlet' mean?", options: ["A dark blue color", "A bright red color", "A light yellow color", "A pale green color"], correctAnswer: "A bright red color" },
      { word: "Oval", questionText: "What does 'oval' mean?", options: ["A shape with four equal sides", "A rounded shape like an egg", "A shape with three sides", "A perfectly round shape"], correctAnswer: "A rounded shape like an egg" },
      { word: "Turquoise", questionText: "What does 'turquoise' mean?", options: ["A dark purple color", "A blue-green color", "A bright orange color", "A pale pink color"], correctAnswer: "A blue-green color" },
      { word: "Diamond", questionText: "What is a 'diamond' shape?", options: ["A shape with three sides", "A square tilted on its corner", "A perfectly round shape", "A rectangular shape"], correctAnswer: "A square tilted on its corner" },
      { word: "Beige", questionText: "What does 'beige' mean?", options: ["A very dark color", "A pale sandy color", "A bright neon color", "A metallic silver color"], correctAnswer: "A pale sandy color" },
      { word: "Cylinder", questionText: "What does 'cylinder' mean?", options: ["A flat round shape", "A 3D shape like a can or tube", "A shape with eight sides", "A pointed shape"], correctAnswer: "A 3D shape like a can or tube" },
      { word: "Crimson", questionText: "What does 'crimson' mean?", options: ["A deep blue color", "A deep red color", "A bright green color", "A pale orange color"], correctAnswer: "A deep red color" },
      { word: "Pentagon", questionText: "What does 'pentagon' mean?", options: ["A shape with four sides", "A shape with five sides", "A shape with six sides", "A shape with eight sides"], correctAnswer: "A shape with five sides" },
      { word: "Ivory", questionText: "What does 'ivory' mean?", options: ["A pure black color", "A creamy white color", "A metallic gold color", "A light blue color"], correctAnswer: "A creamy white color" },
      { word: "Hexagon", questionText: "What does 'hexagon' mean?", options: ["A shape with four sides", "A shape with five sides", "A shape with six sides", "A shape with seven sides"], correctAnswer: "A shape with six sides" },
    ],
  },
  {
    level: "beginner", order: 4, theme: "Family Members",
    title: "Family and Relationships",
    description: "Learn words for family members and relationships.",
    estimatedMinutes: 10,
    questions: [
      { word: "Sibling", questionText: "What does 'sibling' mean?", options: ["A parent", "A brother or sister", "A cousin", "A grandparent"], correctAnswer: "A brother or sister" },
      { word: "Nephew", questionText: "What does 'nephew' mean?", options: ["Your uncle's wife", "The son of your brother or sister", "Your father's brother", "Your cousin's child"], correctAnswer: "The son of your brother or sister" },
      { word: "Niece", questionText: "What does 'niece' mean?", options: ["The daughter of your brother or sister", "Your mother's sister", "Your cousin's daughter", "Your grandmother"], correctAnswer: "The daughter of your brother or sister" },
      { word: "Ancestor", questionText: "What does 'ancestor' mean?", options: ["A future generation", "A person from whom you are descended", "A distant cousin", "A family friend"], correctAnswer: "A person from whom you are descended" },
      { word: "Guardian", questionText: "What does 'guardian' mean?", options: ["A distant relative", "A person who is legally responsible for a child", "A family doctor", "A school teacher"], correctAnswer: "A person who is legally responsible for a child" },
      { word: "Spouse", questionText: "What does 'spouse' mean?", options: ["A close friend", "A husband or wife", "A sibling", "A parent"], correctAnswer: "A husband or wife" },
      { word: "Orphan", questionText: "What does 'orphan' mean?", options: ["A child with no siblings", "A child whose parents have died", "A child who lives abroad", "A child with one parent"], correctAnswer: "A child whose parents have died" },
      { word: "Relative", questionText: "What does 'relative' mean?", options: ["A close friend", "A person connected to you by family", "A neighbor", "A colleague"], correctAnswer: "A person connected to you by family" },
      { word: "Twin", questionText: "What does 'twin' mean?", options: ["An older sibling", "One of two children born at the same time", "A younger sibling", "An adopted child"], correctAnswer: "One of two children born at the same time" },
      { word: "Godparent", questionText: "What does 'godparent' mean?", options: ["A grandparent", "A person who sponsors a child at baptism", "A stepparent", "An adoptive parent"], correctAnswer: "A person who sponsors a child at baptism" },
    ],
  },
  {
    level: "beginner", order: 5, theme: "Nature and Weather",
    title: "Nature and Weather Words",
    description: "Learn words to describe nature and weather.",
    estimatedMinutes: 10,
    questions: [
      { word: "Breeze", questionText: "What does 'breeze' mean?", options: ["A heavy storm", "A light gentle wind", "A type of rain", "A strong hurricane"], correctAnswer: "A light gentle wind" },
      { word: "Petal", questionText: "What does 'petal' mean?", options: ["A leaf on a tree", "One of the colored parts of a flower", "A type of root", "A part of a stem"], correctAnswer: "One of the colored parts of a flower" },
      { word: "Dew", questionText: "What does 'dew' mean?", options: ["A type of rain", "Small water drops on grass in the morning", "A type of mist", "Snow on the ground"], correctAnswer: "Small water drops on grass in the morning" },
      { word: "Thunder", questionText: "What does 'thunder' mean?", options: ["A flash of light in the sky", "The loud sound during a storm", "A type of wind", "Heavy rainfall"], correctAnswer: "The loud sound during a storm" },
      { word: "Meadow", questionText: "What does 'meadow' mean?", options: ["A dense forest", "An open field of grass", "A rocky mountain", "A dry desert"], correctAnswer: "An open field of grass" },
      { word: "Frost", questionText: "What does 'frost' mean?", options: ["Heavy snow", "A thin layer of ice on surfaces in cold weather", "A strong cold wind", "Frozen rain"], correctAnswer: "A thin layer of ice on surfaces in cold weather" },
      { word: "Cliff", questionText: "What does 'cliff' mean?", options: ["A gentle hill", "A steep rock face at the edge of the sea or land", "A flat sandy beach", "A small stream"], correctAnswer: "A steep rock face at the edge of the sea or land" },
      { word: "Puddle", questionText: "What does 'puddle' mean?", options: ["A large lake", "A small pool of water on the ground", "A type of stream", "A deep well"], correctAnswer: "A small pool of water on the ground" },
      { word: "Fog", questionText: "What does 'fog' mean?", options: ["Heavy rain", "Thick cloud close to the ground making it hard to see", "A light breeze", "A type of snow"], correctAnswer: "Thick cloud close to the ground making it hard to see" },
      { word: "Pebble", questionText: "What does 'pebble' mean?", options: ["A large boulder", "A small smooth stone", "A type of sand", "A piece of wood"], correctAnswer: "A small smooth stone" },
    ],
  },
  {
    level: "beginner", order: 6, theme: "Action Words",
    title: "Common Action Words (Verbs)",
    description: "Learn everyday action words.",
    estimatedMinutes: 10,
    questions: [
      { word: "Whisper", questionText: "What does 'whisper' mean?", options: ["To speak very loudly", "To speak very softly", "To sing a song", "To shout angrily"], correctAnswer: "To speak very softly" },
      { word: "Stumble", questionText: "What does 'stumble' mean?", options: ["To run fast", "To almost fall while walking", "To jump high", "To swim quickly"], correctAnswer: "To almost fall while walking" },
      { word: "Glance", questionText: "What does 'glance' mean?", options: ["To stare for a long time", "To look quickly", "To close your eyes", "To blink rapidly"], correctAnswer: "To look quickly" },
      { word: "Gather", questionText: "What does 'gather' mean?", options: ["To spread things apart", "To collect or bring things together", "To throw things away", "To hide things"], correctAnswer: "To collect or bring things together" },
      { word: "Wander", questionText: "What does 'wander' mean?", options: ["To walk with purpose", "To walk without a fixed direction", "To run in circles", "To stand still"], correctAnswer: "To walk without a fixed direction" },
      { word: "Squeeze", questionText: "What does 'squeeze' mean?", options: ["To push firmly", "To press something tightly", "To pull something apart", "To lift something heavy"], correctAnswer: "To press something tightly" },
      { word: "Shiver", questionText: "What does 'shiver' mean?", options: ["To sweat in heat", "To shake because of cold or fear", "To stretch your body", "To yawn when tired"], correctAnswer: "To shake because of cold or fear" },
      { word: "Fetch", questionText: "What does 'fetch' mean?", options: ["To throw something away", "To go and get something and bring it back", "To hide something", "To break something"], correctAnswer: "To go and get something and bring it back" },
      { word: "Mend", questionText: "What does 'mend' mean?", options: ["To break something", "To repair something that is damaged", "To throw something out", "To clean something"], correctAnswer: "To repair something that is damaged" },
      { word: "Crawl", questionText: "What does 'crawl' mean?", options: ["To run on two legs", "To move on hands and knees", "To jump over something", "To fly through the air"], correctAnswer: "To move on hands and knees" },
    ],
  },
  {
    level: "beginner", order: 7, theme: "Describing People",
    title: "Words to Describe People",
    description: "Learn adjectives to describe people's appearance and personality.",
    estimatedMinutes: 10,
    questions: [
      { word: "Cheerful", questionText: "What does 'cheerful' mean?", options: ["Very sad and quiet", "Noticeably happy and optimistic", "Very shy and quiet", "Angry and upset"], correctAnswer: "Noticeably happy and optimistic" },
      { word: "Slim", questionText: "What does 'slim' mean?", options: ["Very tall", "Thin in an attractive way", "Very short", "Very strong"], correctAnswer: "Thin in an attractive way" },
      { word: "Stubborn", questionText: "What does 'stubborn' mean?", options: ["Very flexible", "Unwilling to change opinions or behavior", "Very kind and gentle", "Extremely shy"], correctAnswer: "Unwilling to change opinions or behavior" },
      { word: "Generous", questionText: "What does 'generous' mean?", options: ["Selfish and greedy", "Willing to give more than expected", "Very loud and noisy", "Extremely lazy"], correctAnswer: "Willing to give more than expected" },
      { word: "Clumsy", questionText: "What does 'clumsy' mean?", options: ["Very graceful", "Tending to drop or break things", "Very careful", "Extremely fast"], correctAnswer: "Tending to drop or break things" },
      { word: "Witty", questionText: "What does 'witty' mean?", options: ["Very serious", "Clever and funny in speech", "Very quiet and shy", "Extremely brave"], correctAnswer: "Clever and funny in speech" },
      { word: "Timid", questionText: "What does 'timid' mean?", options: ["Very loud and bold", "Lacking confidence and easily frightened", "Very strong and powerful", "Extremely talkative"], correctAnswer: "Lacking confidence and easily frightened" },
      { word: "Elegant", questionText: "What does 'elegant' mean?", options: ["Messy and disorganized", "Graceful and stylish in appearance", "Very casual and relaxed", "Extremely simple"], correctAnswer: "Graceful and stylish in appearance" },
      { word: "Reliable", questionText: "What does 'reliable' mean?", options: ["Unpredictable and untrustworthy", "Consistently good and can be trusted", "Very exciting and adventurous", "Extremely forgetful"], correctAnswer: "Consistently good and can be trusted" },
      { word: "Arrogant", questionText: "What does 'arrogant' mean?", options: ["Very humble and modest", "Having an exaggerated sense of one's own importance", "Very kind to others", "Extremely careful"], correctAnswer: "Having an exaggerated sense of one's own importance" },
    ],
  },
  {
    level: "beginner", order: 8, theme: "Places in Town",
    title: "Places Around Town",
    description: "Learn words for places you find in a town or city.",
    estimatedMinutes: 10,
    questions: [
      { word: "Library", questionText: "What does 'library' mean?", options: ["A place to buy books", "A place where you can borrow books", "A place to print documents", "A place to study medicine"], correctAnswer: "A place where you can borrow books" },
      { word: "Pharmacy", questionText: "What does 'pharmacy' mean?", options: ["A place to buy food", "A place where medicines are sold", "A place to see a doctor", "A place to buy clothes"], correctAnswer: "A place where medicines are sold" },
      { word: "Stadium", questionText: "What does 'stadium' mean?", options: ["A shopping center", "A large sports ground with seats for spectators", "A type of theater", "A government building"], correctAnswer: "A large sports ground with seats for spectators" },
      { word: "Bakery", questionText: "What does 'bakery' mean?", options: ["A place where clothes are made", "A place where bread and cakes are made and sold", "A place where shoes are repaired", "A place where cars are fixed"], correctAnswer: "A place where bread and cakes are made and sold" },
      { word: "Museum", questionText: "What does 'museum' mean?", options: ["A place to watch movies", "A building where historical objects are displayed", "A place to buy antiques", "A government office"], correctAnswer: "A building where historical objects are displayed" },
      { word: "Clinic", questionText: "What does 'clinic' mean?", options: ["A large hospital", "A small medical facility for outpatients", "A dental school", "A pharmacy"], correctAnswer: "A small medical facility for outpatients" },
      { word: "Embassy", questionText: "What does 'embassy' mean?", options: ["A type of hotel", "The official office of a country's ambassador in another country", "A government court", "A military base"], correctAnswer: "The official office of a country's ambassador in another country" },
      { word: "Warehouse", questionText: "What does 'warehouse' mean?", options: ["A water treatment plant", "A large building for storing goods", "A type of factory", "A shopping mall"], correctAnswer: "A large building for storing goods" },
      { word: "Fountain", questionText: "What does 'fountain' mean?", options: ["A small pond", "A structure that shoots water into the air decoratively", "A type of waterfall", "A swimming pool"], correctAnswer: "A structure that shoots water into the air decoratively" },
      { word: "Pavement", questionText: "What does 'pavement' mean?", options: ["The road for vehicles", "The paved path beside a road for pedestrians", "A parking area", "A bicycle lane"], correctAnswer: "The paved path beside a road for pedestrians" },
    ],
  },
  {
    level: "beginner", order: 9, theme: "Time and Days",
    title: "Time, Days and Months",
    description: "Learn words related to time, days and months.",
    estimatedMinutes: 10,
    questions: [
      { word: "Dawn", questionText: "What does 'dawn' mean?", options: ["The middle of the night", "The time when the sun first rises", "Late afternoon", "Early evening"], correctAnswer: "The time when the sun first rises" },
      { word: "Dusk", questionText: "What does 'dusk' mean?", options: ["Early morning", "The time just after the sun sets", "The middle of the day", "Late at night"], correctAnswer: "The time just after the sun sets" },
      { word: "Decade", questionText: "What does 'decade' mean?", options: ["A period of 5 years", "A period of 10 years", "A period of 20 years", "A period of 100 years"], correctAnswer: "A period of 10 years" },
      { word: "Century", questionText: "What does 'century' mean?", options: ["A period of 10 years", "A period of 50 years", "A period of 100 years", "A period of 1000 years"], correctAnswer: "A period of 100 years" },
      { word: "Fortnight", questionText: "What does 'fortnight' mean?", options: ["A period of 7 days", "A period of 14 days", "A period of 21 days", "A period of 30 days"], correctAnswer: "A period of 14 days" },
      { word: "Midnight", questionText: "What does 'midnight' mean?", options: ["6 in the evening", "12 o'clock at night", "3 in the morning", "Early dawn"], correctAnswer: "12 o'clock at night" },
      { word: "Quarterly", questionText: "What does 'quarterly' mean?", options: ["Happening every month", "Happening every three months", "Happening every six months", "Happening every year"], correctAnswer: "Happening every three months" },
      { word: "Annual", questionText: "What does 'annual' mean?", options: ["Happening every day", "Happening every week", "Happening every month", "Happening every year"], correctAnswer: "Happening every year" },
      { word: "Noon", questionText: "What does 'noon' mean?", options: ["Early morning", "12 o'clock in the middle of the day", "Late afternoon", "Early evening"], correctAnswer: "12 o'clock in the middle of the day" },
      { word: "Era", questionText: "What does 'era' mean?", options: ["A single year", "A long distinct period of history", "A specific day", "A short moment"], correctAnswer: "A long distinct period of history" },
    ],
  },
  {
    level: "beginner", order: 10, theme: "Feelings and Emotions",
    title: "Feelings and Emotions",
    description: "Learn words to describe how people feel.",
    estimatedMinutes: 10,
    questions: [
      { word: "Anxious", questionText: "What does 'anxious' mean?", options: ["Very happy and relaxed", "Worried and nervous about something", "Very angry and loud", "Tired and sleepy"], correctAnswer: "Worried and nervous about something" },
      { word: "Content", questionText: "What does 'content' mean?", options: ["Very excited", "Peacefully happy and satisfied", "Very sad", "Extremely bored"], correctAnswer: "Peacefully happy and satisfied" },
      { word: "Furious", questionText: "What does 'furious' mean?", options: ["Very calm", "Extremely angry", "Very happy", "Slightly annoyed"], correctAnswer: "Extremely angry" },
      { word: "Lonely", questionText: "What does 'lonely' mean?", options: ["Feeling happy alone", "Feeling sad because you have no company", "Feeling tired", "Feeling excited"], correctAnswer: "Feeling sad because you have no company" },
      { word: "Embarrassed", questionText: "What does 'embarrassed' mean?", options: ["Feeling proud", "Feeling self-conscious and ashamed", "Feeling angry", "Feeling excited"], correctAnswer: "Feeling self-conscious and ashamed" },
      { word: "Relieved", questionText: "What does 'relieved' mean?", options: ["Still worried", "Feeling relaxed after worry or danger has passed", "Feeling sad", "Feeling confused"], correctAnswer: "Feeling relaxed after worry or danger has passed" },
      { word: "Jealous", questionText: "What does 'jealous' mean?", options: ["Feeling happy for others", "Feeling upset because someone has what you want", "Feeling proud", "Feeling confused"], correctAnswer: "Feeling upset because someone has what you want" },
      { word: "Overwhelmed", questionText: "What does 'overwhelmed' mean?", options: ["Feeling completely in control", "Feeling buried under too much emotion or work", "Feeling very bored", "Feeling very happy"], correctAnswer: "Feeling buried under too much emotion or work" },
      { word: "Curious", questionText: "What does 'curious' mean?", options: ["Not interested in anything", "Eager to know or learn something", "Very shy", "Very tired"], correctAnswer: "Eager to know or learn something" },
      { word: "Proud", questionText: "What does 'proud' mean?", options: ["Feeling ashamed", "Feeling pleased about your own achievements", "Feeling nervous", "Feeling confused"], correctAnswer: "Feeling pleased about your own achievements" },
    ],
  },

  // ─── INTERMEDIATE ────────────────────────────────────────
  {
    level: "intermediate", order: 1, theme: "Academic Vocabulary",
    title: "Academic and Study Words",
    description: "Learn vocabulary used in academic and educational settings.",
    estimatedMinutes: 10,
    questions: [
      { word: "Analyze", questionText: "What does 'analyze' mean?", options: ["To ignore details", "To examine something in detail", "To summarize briefly", "To memorize facts"], correctAnswer: "To examine something in detail" },
      { word: "Hypothesis", questionText: "What does 'hypothesis' mean?", options: ["A proven fact", "A suggested explanation made for further investigation", "A final conclusion", "A research method"], correctAnswer: "A suggested explanation made for further investigation" },
      { word: "Evaluate", questionText: "What does 'evaluate' mean?", options: ["To collect data", "To assess the value or quality of something", "To create a new theory", "To memorize information"], correctAnswer: "To assess the value or quality of something" },
      { word: "Concise", questionText: "What does 'concise' mean?", options: ["Very long and detailed", "Giving a lot of information clearly in few words", "Very confusing", "Poorly organized"], correctAnswer: "Giving a lot of information clearly in few words" },
      { word: "Plagiarism", questionText: "What does 'plagiarism' mean?", options: ["Original research", "Using someone else's work without giving credit", "A writing style", "A research method"], correctAnswer: "Using someone else's work without giving credit" },
      { word: "Thesis", questionText: "What does 'thesis' mean?", options: ["A short quiz", "A long piece of writing on a specific subject", "A classroom discussion", "A reading assignment"], correctAnswer: "A long piece of writing on a specific subject" },
      { word: "Abstract", questionText: "What does 'abstract' (in academic writing) mean?", options: ["The main body of a paper", "A short summary of a research paper", "The bibliography section", "The introduction"], correctAnswer: "A short summary of a research paper" },
      { word: "Debate", questionText: "What does 'debate' mean?", options: ["A written assignment", "A formal discussion of opposing viewpoints", "A type of exam", "A group project"], correctAnswer: "A formal discussion of opposing viewpoints" },
      { word: "Curriculum", questionText: "What does 'curriculum' mean?", options: ["A school building", "The subjects and content taught in a school", "A student's grades", "A teaching method"], correctAnswer: "The subjects and content taught in a school" },
      { word: "Infer", questionText: "What does 'infer' mean?", options: ["To state facts directly", "To conclude from evidence without being told directly", "To memorize information", "To write a summary"], correctAnswer: "To conclude from evidence without being told directly" },
    ],
  },
  {
    level: "intermediate", order: 2, theme: "Technology Words",
    title: "Technology and Digital Vocabulary",
    description: "Learn words related to technology and the digital world.",
    estimatedMinutes: 10,
    questions: [
      { word: "Algorithm", questionText: "What does 'algorithm' mean?", options: ["A computer virus", "A set of rules for solving a problem", "A type of software", "A computer screen"], correctAnswer: "A set of rules for solving a problem" },
      { word: "Bandwidth", questionText: "What does 'bandwidth' mean?", options: ["The size of a screen", "The rate at which data is transferred over a network", "A type of cable", "The speed of a processor"], correctAnswer: "The rate at which data is transferred over a network" },
      { word: "Encryption", questionText: "What does 'encryption' mean?", options: ["Deleting files permanently", "Converting data into a coded form to prevent access", "Speeding up a computer", "Connecting to the internet"], correctAnswer: "Converting data into a coded form to prevent access" },
      { word: "Interface", questionText: "What does 'interface' mean?", options: ["A computer virus", "The point where two systems meet and interact", "A type of keyboard", "A screen resolution"], correctAnswer: "The point where two systems meet and interact" },
      { word: "Download", questionText: "What does 'download' mean?", options: ["To send data from your device to another", "To receive and save data from the internet", "To delete files", "To print a document"], correctAnswer: "To receive and save data from the internet" },
      { word: "Malware", questionText: "What does 'malware' mean?", options: ["Useful software", "Software designed to damage or disrupt systems", "A hardware component", "A type of internet connection"], correctAnswer: "Software designed to damage or disrupt systems" },
      { word: "Cloud", questionText: "What does 'cloud' (in technology) mean?", options: ["Weather forecasting software", "Remote servers used to store and access data online", "A type of operating system", "A physical hard drive"], correctAnswer: "Remote servers used to store and access data online" },
      { word: "Prototype", questionText: "What does 'prototype' mean?", options: ["A finished product", "A first working model of a new product", "A type of software update", "A computer program"], correctAnswer: "A first working model of a new product" },
      { word: "Cache", questionText: "What does 'cache' mean?", options: ["Deleted files", "Temporary stored data for faster access", "A type of virus", "A firewall setting"], correctAnswer: "Temporary stored data for faster access" },
      { word: "Wireless", questionText: "What does 'wireless' mean?", options: ["Using physical cables to connect", "Transmitting data without physical connections", "A type of broken device", "A slow internet connection"], correctAnswer: "Transmitting data without physical connections" },
    ],
  },
  {
    level: "intermediate", order: 3, theme: "Business and Work",
    title: "Business and Workplace Vocabulary",
    description: "Learn words used in professional and business environments.",
    estimatedMinutes: 10,
    questions: [
      { word: "Revenue", questionText: "What does 'revenue' mean?", options: ["Money spent on expenses", "Income generated by a business", "A type of tax", "A business loss"], correctAnswer: "Income generated by a business" },
      { word: "Negotiate", questionText: "What does 'negotiate' mean?", options: ["To refuse an offer", "To discuss to reach a mutual agreement", "To sign a contract", "To fire an employee"], correctAnswer: "To discuss to reach a mutual agreement" },
      { word: "Deadline", questionText: "What does 'deadline' mean?", options: ["A new project", "The latest time by which something must be completed", "A business meeting", "A contract clause"], correctAnswer: "The latest time by which something must be completed" },
      { word: "Colleague", questionText: "What does 'colleague' mean?", options: ["A business competitor", "A person you work with", "A company client", "A business manager"], correctAnswer: "A person you work with" },
      { word: "Entrepreneur", questionText: "What does 'entrepreneur' mean?", options: ["A government official", "A person who starts and runs their own business", "A company employee", "A financial advisor"], correctAnswer: "A person who starts and runs their own business" },
      { word: "Invoice", questionText: "What does 'invoice' mean?", options: ["A business contract", "A list of goods or services with prices owed", "A pay slip", "A business report"], correctAnswer: "A list of goods or services with prices owed" },
      { word: "Merger", questionText: "What does 'merger' mean?", options: ["A business closing down", "Two companies combining into one", "A business expansion", "A product launch"], correctAnswer: "Two companies combining into one" },
      { word: "Productivity", questionText: "What does 'productivity' mean?", options: ["The number of employees", "The efficiency of output relative to input", "The company's profit", "The quality of products"], correctAnswer: "The efficiency of output relative to input" },
      { word: "Outsource", questionText: "What does 'outsource' mean?", options: ["To hire more staff internally", "To contract work to an outside company", "To increase production", "To reduce prices"], correctAnswer: "To contract work to an outside company" },
      { word: "Strategy", questionText: "What does 'strategy' mean?", options: ["A daily task list", "A plan designed to achieve a long-term goal", "A business problem", "A financial report"], correctAnswer: "A plan designed to achieve a long-term goal" },
    ],
  },
  {
    level: "intermediate", order: 4, theme: "Health and Medicine",
    title: "Health and Medical Vocabulary",
    description: "Learn words related to health, medicine and the body.",
    estimatedMinutes: 10,
    questions: [
      { word: "Symptom", questionText: "What does 'symptom' mean?", options: ["A type of medicine", "A sign that indicates a disease or condition", "A medical test", "A treatment method"], correctAnswer: "A sign that indicates a disease or condition" },
      { word: "Diagnosis", questionText: "What does 'diagnosis' mean?", options: ["A medical treatment", "The identification of a disease by its symptoms", "A type of surgery", "A hospital ward"], correctAnswer: "The identification of a disease by its symptoms" },
      { word: "Chronic", questionText: "What does 'chronic' mean?", options: ["Lasting only a short time", "Persisting for a long time", "Very painful", "Easily cured"], correctAnswer: "Persisting for a long time" },
      { word: "Vaccine", questionText: "What does 'vaccine' mean?", options: ["A pain reliever", "A substance that stimulates immunity against a disease", "A type of antibiotic", "A surgical tool"], correctAnswer: "A substance that stimulates immunity against a disease" },
      { word: "Prescription", questionText: "What does 'prescription' mean?", options: ["A doctor's bill", "A written instruction from a doctor for medicine", "A medical test result", "A hospital admission form"], correctAnswer: "A written instruction from a doctor for medicine" },
      { word: "Inflammation", questionText: "What does 'inflammation' mean?", options: ["A type of infection", "Redness and swelling in body tissue due to injury or infection", "A bone fracture", "A skin condition"], correctAnswer: "Redness and swelling in body tissue due to injury or infection" },
      { word: "Contagious", questionText: "What does 'contagious' mean?", options: ["Cannot be spread between people", "Able to spread from person to person", "Very painful", "Difficult to treat"], correctAnswer: "Able to spread from person to person" },
      { word: "Immune", questionText: "What does 'immune' mean?", options: ["Vulnerable to disease", "Protected from a particular disease", "Feeling very ill", "Recovering from illness"], correctAnswer: "Protected from a particular disease" },
      { word: "Dosage", questionText: "What does 'dosage' mean?", options: ["The type of medicine", "The amount of medicine to be taken at one time", "The side effects of medicine", "The cost of medicine"], correctAnswer: "The amount of medicine to be taken at one time" },
      { word: "Rehabilitation", questionText: "What does 'rehabilitation' mean?", options: ["A type of surgery", "The process of recovering and regaining abilities after illness", "A medical diagnosis", "A hospital department"], correctAnswer: "The process of recovering and regaining abilities after illness" },
    ],
  },
  {
    level: "intermediate", order: 5, theme: "Environment",
    title: "Environment and Nature Vocabulary",
    description: "Learn words related to the environment and ecology.",
    estimatedMinutes: 10,
    questions: [
      { word: "Ecosystem", questionText: "What does 'ecosystem' mean?", options: ["A type of habitat", "A community of living organisms and their environment", "A weather pattern", "A geographic region"], correctAnswer: "A community of living organisms and their environment" },
      { word: "Biodiversity", questionText: "What does 'biodiversity' mean?", options: ["A single species of animal", "The variety of plant and animal life in a habitat", "A type of pollution", "A climate pattern"], correctAnswer: "The variety of plant and animal life in a habitat" },
      { word: "Emissions", questionText: "What does 'emissions' mean?", options: ["Clean energy produced", "Gases or substances released into the atmosphere", "A type of rainfall", "A water source"], correctAnswer: "Gases or substances released into the atmosphere" },
      { word: "Renewable", questionText: "What does 'renewable' (energy) mean?", options: ["Energy from fossil fuels", "Energy from sources that are naturally replenished", "Energy that causes pollution", "Non-sustainable energy"], correctAnswer: "Energy from sources that are naturally replenished" },
      { word: "Deforestation", questionText: "What does 'deforestation' mean?", options: ["Planting new trees", "The clearing or removal of forests", "Forest conservation", "Tree cultivation"], correctAnswer: "The clearing or removal of forests" },
      { word: "Sustainable", questionText: "What does 'sustainable' mean?", options: ["Harmful to the environment", "Able to be maintained without depleting resources", "Very expensive", "Temporary and short-term"], correctAnswer: "Able to be maintained without depleting resources" },
      { word: "Carbon footprint", questionText: "What does 'carbon footprint' mean?", options: ["A type of fossil fuel", "The total greenhouse gas emissions caused by a person or activity", "A measurement of air quality", "A type of carbon product"], correctAnswer: "The total greenhouse gas emissions caused by a person or activity" },
      { word: "Erosion", questionText: "What does 'erosion' mean?", options: ["The building up of land", "The gradual wearing away of land by water or wind", "A type of flood", "Soil fertilization"], correctAnswer: "The gradual wearing away of land by water or wind" },
      { word: "Conservation", questionText: "What does 'conservation' mean?", options: ["The destruction of natural resources", "The protection and preservation of nature", "A type of pollution", "Industrial development"], correctAnswer: "The protection and preservation of nature" },
      { word: "Drought", questionText: "What does 'drought' mean?", options: ["Excessive rainfall", "A prolonged period of abnormally low rainfall", "A type of flood", "A cold weather condition"], correctAnswer: "A prolonged period of abnormally low rainfall" },
    ],
  },
  {
    level: "intermediate", order: 6, theme: "Travel and Tourism",
    title: "Travel and Tourism Vocabulary",
    description: "Learn words used when travelling and exploring the world.",
    estimatedMinutes: 10,
    questions: [
      { word: "Itinerary", questionText: "What does 'itinerary' mean?", options: ["A travel ticket", "A planned route or schedule for a journey", "A hotel booking", "A travel insurance policy"], correctAnswer: "A planned route or schedule for a journey" },
      { word: "Accommodation", questionText: "What does 'accommodation' mean?", options: ["A travel ticket", "A place to stay during a trip", "A type of transport", "A travel guide"], correctAnswer: "A place to stay during a trip" },
      { word: "Customs", questionText: "What does 'customs' (at an airport) mean?", options: ["A type of tourism", "The official process of checking goods brought into a country", "A travel agency", "A boarding gate"], correctAnswer: "The official process of checking goods brought into a country" },
      { word: "Layover", questionText: "What does 'layover' mean?", options: ["A direct flight", "A stop between flights at an intermediate airport", "A type of boarding pass", "A flight cancellation"], correctAnswer: "A stop between flights at an intermediate airport" },
      { word: "Souvenir", questionText: "What does 'souvenir' mean?", options: ["A travel document", "An object bought as a reminder of a place visited", "A type of local food", "A travel brochure"], correctAnswer: "An object bought as a reminder of a place visited" },
      { word: "Hostel", questionText: "What does 'hostel' mean?", options: ["A luxury hotel", "A cheap accommodation where guests share rooms", "A holiday resort", "A camping site"], correctAnswer: "A cheap accommodation where guests share rooms" },
      { word: "Visa", questionText: "What does 'visa' mean?", options: ["A travel ticket", "An official permission to enter a foreign country", "A type of passport", "A travel insurance"], correctAnswer: "An official permission to enter a foreign country" },
      { word: "Landmark", questionText: "What does 'landmark' mean?", options: ["A type of map", "A famous or easily recognizable place", "A travel route", "A border crossing"], correctAnswer: "A famous or easily recognizable place" },
      { word: "Turbulence", questionText: "What does 'turbulence' mean?", options: ["Smooth flying conditions", "Irregular air movement causing a rough flight", "A type of wind pattern", "Aircraft speed"], correctAnswer: "Irregular air movement causing a rough flight" },
      { word: "Backpacker", questionText: "What does 'backpacker' mean?", options: ["A luxury traveler", "A budget traveler who carries a backpack", "A tour guide", "A travel agent"], correctAnswer: "A budget traveler who carries a backpack" },
    ],
  },
  {
    level: "intermediate", order: 7, theme: "Law and Society",
    title: "Law and Society Vocabulary",
    description: "Learn words related to law, justice and society.",
    estimatedMinutes: 10,
    questions: [
      { word: "Legislation", questionText: "What does 'legislation' mean?", options: ["A court decision", "Laws made by a government", "A legal punishment", "A police investigation"], correctAnswer: "Laws made by a government" },
      { word: "Verdict", questionText: "What does 'verdict' mean?", options: ["A court charge", "The decision made by a jury or judge", "A legal appeal", "A criminal sentence"], correctAnswer: "The decision made by a jury or judge" },
      { word: "Defendant", questionText: "What does 'defendant' mean?", options: ["The judge", "The person accused in a legal case", "The lawyer", "The jury member"], correctAnswer: "The person accused in a legal case" },
      { word: "Justice", questionText: "What does 'justice' mean?", options: ["Breaking the law", "Fair behaviour and treatment under the law", "A type of crime", "A court hearing"], correctAnswer: "Fair behaviour and treatment under the law" },
      { word: "Constitution", questionText: "What does 'constitution' mean?", options: ["A court ruling", "The fundamental laws and principles of a country", "A legal contract", "A government budget"], correctAnswer: "The fundamental laws and principles of a country" },
      { word: "Penalty", questionText: "What does 'penalty' mean?", options: ["A reward for good behavior", "A punishment for breaking a rule or law", "A legal right", "A court fee"], correctAnswer: "A punishment for breaking a rule or law" },
      { word: "Testimony", questionText: "What does 'testimony' mean?", options: ["A legal document", "A formal statement given as evidence in court", "A court order", "A lawyer's argument"], correctAnswer: "A formal statement given as evidence in court" },
      { word: "Corruption", questionText: "What does 'corruption' mean?", options: ["Good governance", "Dishonest behavior by people in power for personal gain", "Legal reform", "A type of protest"], correctAnswer: "Dishonest behavior by people in power for personal gain" },
      { word: "Bail", questionText: "What does 'bail' mean?", options: ["A prison sentence", "Money paid to release a prisoner temporarily before trial", "A court fine", "A legal appeal"], correctAnswer: "Money paid to release a prisoner temporarily before trial" },
      { word: "Lawsuit", questionText: "What does 'lawsuit' mean?", options: ["A legal document", "A legal case brought to court", "A court verdict", "A legal right"], correctAnswer: "A legal case brought to court" },
    ],
  },
  {
    level: "intermediate", order: 8, theme: "Arts and Culture",
    title: "Arts, Culture and Literature Vocabulary",
    description: "Learn words related to arts, culture and creative expression.",
    estimatedMinutes: 10,
    questions: [
      { word: "Aesthetic", questionText: "What does 'aesthetic' mean?", options: ["Related to logic", "Related to the appreciation of beauty", "Related to science", "Related to mathematics"], correctAnswer: "Related to the appreciation of beauty" },
      { word: "Narrative", questionText: "What does 'narrative' mean?", options: ["A type of poem", "A spoken or written account of events", "A painting style", "A musical genre"], correctAnswer: "A spoken or written account of events" },
      { word: "Metaphor", questionText: "What does 'metaphor' mean?", options: ["A type of rhyme", "A figure of speech comparing things without 'like' or 'as'", "A story structure", "A type of poem"], correctAnswer: "A figure of speech comparing things without 'like' or 'as'" },
      { word: "Genre", questionText: "What does 'genre' mean?", options: ["A specific author", "A category of artistic or literary work", "A writing style", "A type of language"], correctAnswer: "A category of artistic or literary work" },
      { word: "Satire", questionText: "What does 'satire' mean?", options: ["A type of tragedy", "The use of humor to criticize society or individuals", "A romantic story", "A historical account"], correctAnswer: "The use of humor to criticize society or individuals" },
      { word: "Mosaic", questionText: "What does 'mosaic' mean?", options: ["A type of painting", "A picture made by arranging small colored pieces", "A type of sculpture", "A digital artwork"], correctAnswer: "A picture made by arranging small colored pieces" },
      { word: "Symphony", questionText: "What does 'symphony' mean?", options: ["A short song", "A long complex musical composition for an orchestra", "A type of opera", "A musical instrument"], correctAnswer: "A long complex musical composition for an orchestra" },
      { word: "Dialect", questionText: "What does 'dialect' mean?", options: ["A foreign language", "A form of a language spoken in a specific region", "A type of accent", "A writing style"], correctAnswer: "A form of a language spoken in a specific region" },
      { word: "Curator", questionText: "What does 'curator' mean?", options: ["An artist", "A person who manages and organizes a museum or exhibition", "A museum visitor", "An art teacher"], correctAnswer: "A person who manages and organizes a museum or exhibition" },
      { word: "Prose", questionText: "What does 'prose' mean?", options: ["A type of poem with rhyme", "Ordinary written language without poetic structure", "A type of drama", "A musical composition"], correctAnswer: "Ordinary written language without poetic structure" },
    ],
  },
  {
    level: "intermediate", order: 9, theme: "Psychology and Mind",
    title: "Psychology and Human Behavior",
    description: "Learn words related to the mind and human behavior.",
    estimatedMinutes: 10,
    questions: [
      { word: "Perception", questionText: "What does 'perception' mean?", options: ["A physical action", "The way one interprets and understands things", "A type of memory", "A physical sensation"], correctAnswer: "The way one interprets and understands things" },
      { word: "Motivation", questionText: "What does 'motivation' mean?", options: ["A feeling of sadness", "The reason for acting or behaving in a certain way", "A type of emotion", "A psychological disorder"], correctAnswer: "The reason for acting or behaving in a certain way" },
      { word: "Empathy", questionText: "What does 'empathy' mean?", options: ["Feeling superior to others", "The ability to understand and share another's feelings", "Ignoring others' feelings", "Giving advice to others"], correctAnswer: "The ability to understand and share another's feelings" },
      { word: "Bias", questionText: "What does 'bias' mean?", options: ["A fair judgment", "An unfair preference or prejudice for or against something", "An honest opinion", "A balanced view"], correctAnswer: "An unfair preference or prejudice for or against something" },
      { word: "Subconscious", questionText: "What does 'subconscious' mean?", options: ["Fully aware thoughts", "Part of the mind below full conscious awareness", "A type of memory", "A mental disorder"], correctAnswer: "Part of the mind below full conscious awareness" },
      { word: "Trauma", questionText: "What does 'trauma' mean?", options: ["A positive life event", "A deeply distressing experience that has lasting effects", "A type of therapy", "A mental strength"], correctAnswer: "A deeply distressing experience that has lasting effects" },
      { word: "Cognitive", questionText: "What does 'cognitive' mean?", options: ["Related to physical health", "Related to mental processes like thinking and learning", "Related to emotions", "Related to social behavior"], correctAnswer: "Related to mental processes like thinking and learning" },
      { word: "Resilience", questionText: "What does 'resilience' mean?", options: ["The inability to cope with stress", "The ability to recover quickly from difficulties", "A type of mental illness", "A negative personality trait"], correctAnswer: "The ability to recover quickly from difficulties" },
      { word: "Stereotype", questionText: "What does 'stereotype' mean?", options: ["An individual assessment", "A fixed oversimplified image of a group of people", "A fair judgment", "A personal opinion"], correctAnswer: "A fixed oversimplified image of a group of people" },
      { word: "Inhibition", questionText: "What does 'inhibition' mean?", options: ["Freedom of expression", "A feeling that makes one unable to act in a relaxed way", "A type of confidence", "A social skill"], correctAnswer: "A feeling that makes one unable to act in a relaxed way" },
    ],
  },
  {
    level: "intermediate", order: 10, theme: "Economics and Finance",
    title: "Economics and Finance Vocabulary",
    description: "Learn words related to economics, money and finance.",
    estimatedMinutes: 10,
    questions: [
      { word: "Inflation", questionText: "What does 'inflation' mean?", options: ["A decrease in prices", "A general increase in prices over time", "A type of tax", "A business profit"], correctAnswer: "A general increase in prices over time" },
      { word: "Recession", questionText: "What does 'recession' mean?", options: ["Economic growth", "A period of temporary economic decline", "A rise in employment", "An increase in trade"], correctAnswer: "A period of temporary economic decline" },
      { word: "Budget", questionText: "What does 'budget' mean?", options: ["A bank account", "A plan for managing income and expenses", "A type of loan", "A financial investment"], correctAnswer: "A plan for managing income and expenses" },
      { word: "Interest rate", questionText: "What does 'interest rate' mean?", options: ["A bank fee", "The percentage charged for borrowing money", "A type of tax", "A savings account"], correctAnswer: "The percentage charged for borrowing money" },
      { word: "Subsidy", questionText: "What does 'subsidy' mean?", options: ["A type of tax", "Money given by the government to help an industry", "A business loan", "A financial penalty"], correctAnswer: "Money given by the government to help an industry" },
      { word: "Dividend", questionText: "What does 'dividend' mean?", options: ["A company debt", "A sum of money paid to shareholders from profits", "A business tax", "A type of loan"], correctAnswer: "A sum of money paid to shareholders from profits" },
      { word: "Deficit", questionText: "What does 'deficit' mean?", options: ["A financial surplus", "When expenditure exceeds income", "A type of profit", "A business investment"], correctAnswer: "When expenditure exceeds income" },
      { word: "Commodity", questionText: "What does 'commodity' mean?", options: ["A luxury item", "A raw material or primary product that can be traded", "A type of currency", "A financial service"], correctAnswer: "A raw material or primary product that can be traded" },
      { word: "Tariff", questionText: "What does 'tariff' mean?", options: ["A type of trade agreement", "A tax imposed on imported goods", "A business license", "A type of subsidy"], correctAnswer: "A tax imposed on imported goods" },
      { word: "Portfolio", questionText: "What does 'portfolio' mean?", options: ["A single investment", "A collection of investments held by a person", "A business plan", "A financial report"], correctAnswer: "A collection of investments held by a person" },
    ],
  },

  // ─── ADVANCED ────────────────────────────────────────────
  {
    level: "advanced", order: 1, theme: "Philosophy and Ethics",
    title: "Philosophy and Ethics Vocabulary",
    description: "Learn sophisticated words used in philosophical and ethical discussion.",
    estimatedMinutes: 10,
    questions: [
      { word: "Epistemology", questionText: "What does 'epistemology' mean?", options: ["The study of the universe", "The branch of philosophy concerned with knowledge", "The study of ethics", "The study of language"], correctAnswer: "The branch of philosophy concerned with knowledge" },
      { word: "Nihilism", questionText: "What does 'nihilism' mean?", options: ["A belief in universal meaning", "The belief that life has no meaning or purpose", "A religious philosophy", "A political ideology"], correctAnswer: "The belief that life has no meaning or purpose" },
      { word: "Utilitarianism", questionText: "What does 'utilitarianism' mean?", options: ["A belief in individual rights", "The doctrine that actions are right if they benefit the majority", "A religious philosophy", "A belief in absolute truth"], correctAnswer: "The doctrine that actions are right if they benefit the majority" },
      { word: "Paradox", questionText: "What does 'paradox' mean?", options: ["A simple truth", "A statement that seems contradictory but may be true", "A logical proof", "A scientific theory"], correctAnswer: "A statement that seems contradictory but may be true" },
      { word: "Empiricism", questionText: "What does 'empiricism' mean?", options: ["Knowledge based on pure reason", "The theory that knowledge comes from sensory experience", "A political philosophy", "A religious belief"], correctAnswer: "The theory that knowledge comes from sensory experience" },
      { word: "Dogma", questionText: "What does 'dogma' mean?", options: ["An open question", "A fixed set of beliefs accepted without question", "A philosophical debate", "A scientific hypothesis"], correctAnswer: "A fixed set of beliefs accepted without question" },
      { word: "Autonomy", questionText: "What does 'autonomy' mean?", options: ["Dependence on others", "The right to self-governance and independence", "A type of authority", "A political system"], correctAnswer: "The right to self-governance and independence" },
      { word: "Dialectic", questionText: "What does 'dialectic' mean?", options: ["A type of language", "A method of argument through opposing ideas to find truth", "A logical fallacy", "A scientific method"], correctAnswer: "A method of argument through opposing ideas to find truth" },
      { word: "Altruism", questionText: "What does 'altruism' mean?", options: ["Selfishness", "Selfless concern for the wellbeing of others", "A philosophical debate", "A type of egoism"], correctAnswer: "Selfless concern for the wellbeing of others" },
      { word: "Hegemony", questionText: "What does 'hegemony' mean?", options: ["Equal power distribution", "Dominance or leadership of one group over others", "A type of democracy", "A peaceful cooperation"], correctAnswer: "Dominance or leadership of one group over others" },
    ],
  },
  {
    level: "advanced", order: 2, theme: "Politics and Governance",
    title: "Politics and Governance Vocabulary",
    description: "Learn advanced words used in political and governance contexts.",
    estimatedMinutes: 10,
    questions: [
      { word: "Sovereignty", questionText: "What does 'sovereignty' mean?", options: ["A type of election", "Supreme authority over a territory", "A political party", "A type of government"], correctAnswer: "Supreme authority over a territory" },
      { word: "Autocracy", questionText: "What does 'autocracy' mean?", options: ["Rule by the people", "A system where one person has unlimited power", "A type of democracy", "Rule by elected officials"], correctAnswer: "A system where one person has unlimited power" },
      { word: "Referendum", questionText: "What does 'referendum' mean?", options: ["A government election", "A direct vote by the public on a specific question", "A parliamentary debate", "A political party decision"], correctAnswer: "A direct vote by the public on a specific question" },
      { word: "Lobbying", questionText: "What does 'lobbying' mean?", options: ["Passing new laws", "Attempting to influence politicians on specific issues", "Running for election", "Protesting publicly"], correctAnswer: "Attempting to influence politicians on specific issues" },
      { word: "Bureaucracy", questionText: "What does 'bureaucracy' mean?", options: ["A type of democracy", "A complex system of official rules and processes", "A political party", "A type of election"], correctAnswer: "A complex system of official rules and processes" },
      { word: "Geopolitics", questionText: "What does 'geopolitics' mean?", options: ["Local city planning", "The influence of geography on politics and international relations", "A type of economics", "A military strategy"], correctAnswer: "The influence of geography on politics and international relations" },
      { word: "Veto", questionText: "What does 'veto' mean?", options: ["To approve a law", "The right to reject a decision or proposal", "To pass a bill", "To propose legislation"], correctAnswer: "The right to reject a decision or proposal" },
      { word: "Propaganda", questionText: "What does 'propaganda' mean?", options: ["Balanced news reporting", "Biased information used to promote a political cause", "A type of journalism", "A government policy"], correctAnswer: "Biased information used to promote a political cause" },
      { word: "Coup", questionText: "What does 'coup' mean?", options: ["A peaceful election", "A sudden overthrow of a government", "A type of political reform", "A diplomatic agreement"], correctAnswer: "A sudden overthrow of a government" },
      { word: "Sanctions", questionText: "What does 'sanctions' mean?", options: ["Trade agreements", "Penalties imposed on a country for violating international law", "Military alliances", "Diplomatic negotiations"], correctAnswer: "Penalties imposed on a country for violating international law" },
    ],
  },
  {
    level: "advanced", order: 3, theme: "Science and Research",
    title: "Advanced Science and Research Vocabulary",
    description: "Learn words used in scientific research and academic study.",
    estimatedMinutes: 10,
    questions: [
      { word: "Paradigm", questionText: "What does 'paradigm' mean?", options: ["A scientific mistake", "A typical example or framework of thought", "A research method", "A scientific instrument"], correctAnswer: "A typical example or framework of thought" },
      { word: "Extrapolate", questionText: "What does 'extrapolate' mean?", options: ["To repeat known data", "To extend conclusions beyond known data", "To disprove a theory", "To collect new data"], correctAnswer: "To extend conclusions beyond known data" },
      { word: "Correlation", questionText: "What does 'correlation' mean?", options: ["A proven cause and effect", "A mutual relationship between two variables", "A research error", "A statistical method"], correctAnswer: "A mutual relationship between two variables" },
      { word: "Catalyst", questionText: "What does 'catalyst' mean?", options: ["Something that slows a reaction", "Something that speeds up a process or reaction", "A type of chemical compound", "A research instrument"], correctAnswer: "Something that speeds up a process or reaction" },
      { word: "Anomaly", questionText: "What does 'anomaly' mean?", options: ["An expected result", "Something that deviates from what is normal", "A proven hypothesis", "A standard measurement"], correctAnswer: "Something that deviates from what is normal" },
      { word: "Quantum", questionText: "What does 'quantum' mean?", options: ["A large unit of energy", "The minimum discrete unit of energy", "A type of wave", "A scientific instrument"], correctAnswer: "The minimum discrete unit of energy" },
      { word: "Empirical", questionText: "What does 'empirical' mean?", options: ["Based on theory alone", "Based on observation and evidence", "Based on opinion", "Based on assumption"], correctAnswer: "Based on observation and evidence" },
      { word: "Synthesis", questionText: "What does 'synthesis' mean?", options: ["Breaking things apart", "Combining elements to form a new whole", "Analyzing data", "Collecting samples"], correctAnswer: "Combining elements to form a new whole" },
      { word: "Nomenclature", questionText: "What does 'nomenclature' mean?", options: ["A research method", "A system of names used in a particular field", "A type of classification", "A scientific instrument"], correctAnswer: "A system of names used in a particular field" },
      { word: "Peer review", questionText: "What does 'peer review' mean?", options: ["Self-evaluation of work", "Evaluation of research by experts in the same field", "A type of publication", "A research grant"], correctAnswer: "Evaluation of research by experts in the same field" },
    ],
  },
  {
    level: "advanced", order: 4, theme: "Literary and Rhetorical Devices",
    title: "Literary and Rhetorical Devices",
    description: "Learn sophisticated literary and rhetorical terms.",
    estimatedMinutes: 10,
    questions: [
      { word: "Juxtaposition", questionText: "What does 'juxtaposition' mean?", options: ["Repeating an idea", "Placing contrasting things close together for effect", "A type of rhyme scheme", "A narrative structure"], correctAnswer: "Placing contrasting things close together for effect" },
      { word: "Soliloquy", questionText: "What does 'soliloquy' mean?", options: ["A conversation between two characters", "A speech where a character speaks thoughts aloud alone", "A type of poem", "A narrative summary"], correctAnswer: "A speech where a character speaks thoughts aloud alone" },
      { word: "Hubris", questionText: "What does 'hubris' mean?", options: ["Extreme humility", "Excessive pride leading to downfall", "A type of tragedy", "A narrative climax"], correctAnswer: "Excessive pride leading to downfall" },
      { word: "Allegory", questionText: "What does 'allegory' mean?", options: ["A type of metaphor", "A story with a hidden deeper meaning", "A type of poem", "A literary genre"], correctAnswer: "A story with a hidden deeper meaning" },
      { word: "Catharsis", questionText: "What does 'catharsis' mean?", options: ["Building tension", "The emotional release experienced through art or drama", "A type of conflict", "A narrative climax"], correctAnswer: "The emotional release experienced through art or drama" },
      { word: "Anachronism", questionText: "What does 'anachronism' mean?", options: ["A futuristic element", "Something out of its correct historical period", "A type of flashback", "A narrative device"], correctAnswer: "Something out of its correct historical period" },
      { word: "Motif", questionText: "What does 'motif' mean?", options: ["A single event in a story", "A recurring element that has symbolic significance", "A type of character", "A plot twist"], correctAnswer: "A recurring element that has symbolic significance" },
      { word: "Euphemism", questionText: "What does 'euphemism' mean?", options: ["A harsh direct expression", "A mild word used instead of a harsh or blunt one", "A type of irony", "A literary genre"], correctAnswer: "A mild word used instead of a harsh or blunt one" },
      { word: "Dramatic irony", questionText: "What does 'dramatic irony' mean?", options: ["When all characters know something", "When the audience knows something characters do not", "A type of comedy", "A plot device"], correctAnswer: "When the audience knows something characters do not" },
      { word: "Denouement", questionText: "What does 'denouement' mean?", options: ["The opening of a story", "The final resolution of a story's plot", "The main conflict", "The rising action"], correctAnswer: "The final resolution of a story's plot" },
    ],
  },
  {
    level: "advanced", order: 5, theme: "Global Issues",
    title: "Global Issues and International Relations",
    description: "Learn vocabulary used to discuss complex global issues.",
    estimatedMinutes: 10,
    questions: [
      { word: "Globalization", questionText: "What does 'globalization' mean?", options: ["Isolating countries from each other", "The process of increasing interconnectedness between countries", "A type of trade barrier", "A political movement"], correctAnswer: "The process of increasing interconnectedness between countries" },
      { word: "Diaspora", questionText: "What does 'diaspora' mean?", options: ["A type of migration", "People scattered from their homeland living in other countries", "A refugee camp", "An immigrant community"], correctAnswer: "People scattered from their homeland living in other countries" },
      { word: "Austerity", questionText: "What does 'austerity' mean?", options: ["Economic growth policies", "Strict economic policies reducing government spending", "A type of subsidy", "A financial investment"], correctAnswer: "Strict economic policies reducing government spending" },
      { word: "Multilateral", questionText: "What does 'multilateral' mean?", options: ["Involving two countries", "Involving many countries or parties", "A one-sided agreement", "A type of trade deal"], correctAnswer: "Involving many countries or parties" },
      { word: "Xenophobia", questionText: "What does 'xenophobia' mean?", options: ["Love of foreign cultures", "Fear or hatred of people from other countries", "A type of nationalism", "Cultural appreciation"], correctAnswer: "Fear or hatred of people from other countries" },
      { word: "Imperialism", questionText: "What does 'imperialism' mean?", options: ["A democratic principle", "Extending power over other nations through domination", "A type of trade policy", "A peaceful alliance"], correctAnswer: "Extending power over other nations through domination" },
      { word: "Humanitarian", questionText: "What does 'humanitarian' mean?", options: ["Related to military action", "Concerned with promoting human welfare", "Related to economic policy", "Related to political power"], correctAnswer: "Concerned with promoting human welfare" },
      { word: "Reparations", questionText: "What does 'reparations' mean?", options: ["A peace treaty", "Compensation made for a past wrong", "A type of sanction", "A diplomatic agreement"], correctAnswer: "Compensation made for a past wrong" },
      { word: "Populism", questionText: "What does 'populism' mean?", options: ["A type of democracy", "A political approach appealing to ordinary people against elites", "A conservative ideology", "A type of socialism"], correctAnswer: "A political approach appealing to ordinary people against elites" },
      { word: "Diplomatic", questionText: "What does 'diplomatic' mean?", options: ["Aggressive in dealings", "Skilled in managing international relations tactfully", "Related to military force", "Related to economic policy"], correctAnswer: "Skilled in managing international relations tactfully" },
    ],
  },
  {
    level: "advanced", order: 6, theme: "Cognitive and Academic Skills",
    title: "Critical Thinking and Academic Skills",
    description: "Learn vocabulary for high-level thinking and academic discourse.",
    estimatedMinutes: 10,
    questions: [
      { word: "Conjecture", questionText: "What does 'conjecture' mean?", options: ["A proven conclusion", "An opinion formed without full evidence", "A scientific fact", "A logical proof"], correctAnswer: "An opinion formed without full evidence" },
      { word: "Substantiate", questionText: "What does 'substantiate' mean?", options: ["To disprove an argument", "To provide evidence to support a claim", "To summarize findings", "To question a theory"], correctAnswer: "To provide evidence to support a claim" },
      { word: "Nuance", questionText: "What does 'nuance' mean?", options: ["An obvious difference", "A subtle distinction in meaning or expression", "A major contradiction", "A clear argument"], correctAnswer: "A subtle distinction in meaning or expression" },
      { word: "Rhetoric", questionText: "What does 'rhetoric' mean?", options: ["Plain factual speech", "Persuasive and effective use of language", "A type of logic", "A debate format"], correctAnswer: "Persuasive and effective use of language" },
      { word: "Fallacy", questionText: "What does 'fallacy' mean?", options: ["A correct argument", "A mistaken belief or flawed reasoning", "A proven fact", "A logical conclusion"], correctAnswer: "A mistaken belief or flawed reasoning" },
      { word: "Ambiguous", questionText: "What does 'ambiguous' mean?", options: ["Perfectly clear", "Open to more than one interpretation", "Completely false", "Extremely detailed"], correctAnswer: "Open to more than one interpretation" },
      { word: "Dichotomy", questionText: "What does 'dichotomy' mean?", options: ["A gradual scale", "A division into two completely opposing parts", "A type of argument", "A philosophical debate"], correctAnswer: "A division into two completely opposing parts" },
      { word: "Pragmatic", questionText: "What does 'pragmatic' mean?", options: ["Idealistic and impractical", "Dealing with things in a practical and sensible way", "Theoretical and abstract", "Emotional and irrational"], correctAnswer: "Dealing with things in a practical and sensible way" },
      { word: "Corroborate", questionText: "What does 'corroborate' mean?", options: ["To disprove evidence", "To confirm or support with additional evidence", "To question findings", "To summarize data"], correctAnswer: "To confirm or support with additional evidence" },
      { word: "Implicit", questionText: "What does 'implicit' mean?", options: ["Stated clearly and directly", "Suggested or understood without being stated", "Completely obvious", "Fully explained"], correctAnswer: "Suggested or understood without being stated" },
    ],
  },
  {
    level: "advanced", order: 7, theme: "Psychology and Behavior",
    title: "Advanced Psychology Vocabulary",
    description: "Learn advanced psychological and behavioral terms.",
    estimatedMinutes: 10,
    questions: [
      { word: "Cognitive dissonance", questionText: "What does 'cognitive dissonance' mean?", options: ["Perfect agreement between beliefs", "Mental discomfort from holding conflicting beliefs", "A type of memory loss", "A psychological strength"], correctAnswer: "Mental discomfort from holding conflicting beliefs" },
      { word: "Narcissism", questionText: "What does 'narcissism' mean?", options: ["Extreme self-sacrifice", "Excessive self-admiration and self-centeredness", "A type of empathy", "A social skill"], correctAnswer: "Excessive self-admiration and self-centeredness" },
      { word: "Catharsis", questionText: "What does 'catharsis' mean?", options: ["Building emotional tension", "Emotional release and relief through expression", "A type of anxiety", "A defense mechanism"], correctAnswer: "Emotional release and relief through expression" },
      { word: "Gaslighting", questionText: "What does 'gaslighting' mean?", options: ["Providing honest feedback", "Manipulating someone to question their own reality", "A type of therapy", "A communication skill"], correctAnswer: "Manipulating someone to question their own reality" },
      { word: "Intrinsic motivation", questionText: "What does 'intrinsic motivation' mean?", options: ["Being motivated by external rewards", "Being motivated by internal satisfaction", "A type of peer pressure", "A social influence"], correctAnswer: "Being motivated by internal satisfaction" },
      { word: "Projection", questionText: "What does 'projection' (psychology) mean?", options: ["Accepting your own faults", "Attributing your own feelings to someone else", "A type of empathy", "A coping mechanism"], correctAnswer: "Attributing your own feelings to someone else" },
      { word: "Locus of control", questionText: "What does 'locus of control' mean?", options: ["A type of memory", "The degree to which people believe they control outcomes", "A social behavior", "A type of motivation"], correctAnswer: "The degree to which people believe they control outcomes" },
      { word: "Desensitization", questionText: "What does 'desensitization' mean?", options: ["Becoming more sensitive to stimuli", "Becoming less responsive to something through repeated exposure", "A type of therapy", "An emotional reaction"], correctAnswer: "Becoming less responsive to something through repeated exposure" },
      { word: "Rationalization", questionText: "What does 'rationalization' mean?", options: ["Honest self-reflection", "Justifying actions with logical-sounding reasons to hide true motives", "A type of critical thinking", "Emotional decision making"], correctAnswer: "Justifying actions with logical-sounding reasons to hide true motives" },
      { word: "Schadenfreude", questionText: "What does 'schadenfreude' mean?", options: ["Feeling sad for others", "Pleasure derived from another's misfortune", "A type of empathy", "Feeling guilty about success"], correctAnswer: "Pleasure derived from another's misfortune" },
    ],
  },
  {
    level: "advanced", order: 8, theme: "Economics and Society",
    title: "Advanced Economics and Society",
    description: "Learn sophisticated economic and societal vocabulary.",
    estimatedMinutes: 10,
    questions: [
      { word: "Oligopoly", questionText: "What does 'oligopoly' mean?", options: ["A market with many competitors", "A market controlled by a small number of firms", "A government-controlled market", "A free and open market"], correctAnswer: "A market controlled by a small number of firms" },
      { word: "Neoliberalism", questionText: "What does 'neoliberalism' mean?", options: ["A socialist economic policy", "An economic policy favoring free markets and reduced government", "A type of welfare state", "A protectionist trade policy"], correctAnswer: "An economic policy favoring free markets and reduced government" },
      { word: "Gentrification", questionText: "What does 'gentrification' mean?", options: ["Urban decay", "Renovation of areas causing displacement of lower-income residents", "A type of urban planning", "Building new suburbs"], correctAnswer: "Renovation of areas causing displacement of lower-income residents" },
      { word: "Inequality", questionText: "What does 'inequality' mean?", options: ["Equal distribution of resources", "Unequal distribution of resources or opportunities", "A type of poverty", "A social policy"], correctAnswer: "Unequal distribution of resources or opportunities" },
      { word: "Quantitative easing", questionText: "What does 'quantitative easing' mean?", options: ["Raising interest rates", "A central bank policy of increasing money supply", "Reducing government spending", "A type of taxation"], correctAnswer: "A central bank policy of increasing money supply" },
      { word: "Social mobility", questionText: "What does 'social mobility' mean?", options: ["Moving between cities", "The ability to move between social classes", "A type of migration", "A social welfare program"], correctAnswer: "The ability to move between social classes" },
      { word: "Monopoly", questionText: "What does 'monopoly' mean?", options: ["Competition between many firms", "Exclusive control of a market by one company", "A government-owned business", "A type of trade agreement"], correctAnswer: "Exclusive control of a market by one company" },
      { word: "Fiscal policy", questionText: "What does 'fiscal policy' mean?", options: ["Central bank interest rate decisions", "Government decisions on taxation and spending", "A type of trade policy", "A monetary regulation"], correctAnswer: "Government decisions on taxation and spending" },
      { word: "Philanthropy", questionText: "What does 'philanthropy' mean?", options: ["Profit-driven business", "Charitable giving to promote the welfare of others", "A type of taxation", "A government grant"], correctAnswer: "Charitable giving to promote the welfare of others" },
      { word: "Austerity", questionText: "What does 'austerity' mean?", options: ["Government spending increases", "Government policies of spending cuts to reduce debt", "A type of economic growth", "A monetary policy"], correctAnswer: "Government policies of spending cuts to reduce debt" },
    ],
  },
  {
    level: "advanced", order: 9, theme: "Language and Linguistics",
    title: "Language and Linguistics Vocabulary",
    description: "Learn advanced vocabulary about language and communication.",
    estimatedMinutes: 10,
    questions: [
      { word: "Syntax", questionText: "What does 'syntax' mean?", options: ["The meaning of words", "The rules governing sentence structure", "The sound of language", "The origin of words"], correctAnswer: "The rules governing sentence structure" },
      { word: "Semantics", questionText: "What does 'semantics' mean?", options: ["The study of grammar", "The study of meaning in language", "The study of pronunciation", "The study of writing systems"], correctAnswer: "The study of meaning in language" },
      { word: "Colloquial", questionText: "What does 'colloquial' mean?", options: ["Very formal language", "Used in ordinary informal conversation", "A type of written language", "A technical term"], correctAnswer: "Used in ordinary informal conversation" },
      { word: "Connotation", questionText: "What does 'connotation' mean?", options: ["The literal meaning of a word", "An idea or feeling a word invokes beyond its literal meaning", "The grammatical function of a word", "The origin of a word"], correctAnswer: "An idea or feeling a word invokes beyond its literal meaning" },
      { word: "Etymology", questionText: "What does 'etymology' mean?", options: ["The study of grammar", "The study of the origin and history of words", "The study of pronunciation", "The study of dialects"], correctAnswer: "The study of the origin and history of words" },
      { word: "Ambiguity", questionText: "What does 'ambiguity' mean?", options: ["Perfect clarity of meaning", "The quality of having more than one possible meaning", "A grammatical error", "A type of metaphor"], correctAnswer: "The quality of having more than one possible meaning" },
      { word: "Phonetics", questionText: "What does 'phonetics' mean?", options: ["The study of word meanings", "The study of the sounds of human speech", "The study of writing", "The study of grammar"], correctAnswer: "The study of the sounds of human speech" },
      { word: "Vernacular", questionText: "What does 'vernacular' mean?", options: ["Formal written language", "The language spoken by ordinary people in a region", "A type of dialect", "An ancient language"], correctAnswer: "The language spoken by ordinary people in a region" },
      { word: "Pragmatics", questionText: "What does 'pragmatics' mean?", options: ["The study of grammar rules", "The study of how context influences language meaning", "The study of word origins", "The study of language sounds"], correctAnswer: "The study of how context influences language meaning" },
      { word: "Linguistic relativity", questionText: "What does 'linguistic relativity' mean?", options: ["All languages are identical", "The idea that language influences how we think", "A grammar rule", "A type of translation"], correctAnswer: "The idea that language influences how we think" },
    ],
  },
  {
    level: "advanced", order: 10, theme: "Environmental Science",
    title: "Advanced Environmental Science Vocabulary",
    description: "Learn advanced vocabulary for discussing environmental science.",
    estimatedMinutes: 10,
    questions: [
      { word: "Anthropocene", questionText: "What does 'anthropocene' mean?", options: ["A prehistoric era", "The current geological era defined by human impact on Earth", "A type of fossil", "A climate model"], correctAnswer: "The current geological era defined by human impact on Earth" },
      { word: "Carbon sequestration", questionText: "What does 'carbon sequestration' mean?", options: ["Releasing carbon into the atmosphere", "The process of capturing and storing carbon dioxide", "A type of carbon emission", "A renewable energy process"], correctAnswer: "The process of capturing and storing carbon dioxide" },
      { word: "Tipping point", questionText: "What does 'tipping point' (climate) mean?", options: ["A gradual change", "A threshold beyond which changes become irreversible", "A climate prediction", "A type of weather event"], correctAnswer: "A threshold beyond which changes become irreversible" },
      { word: "Biome", questionText: "What does 'biome' mean?", options: ["A single species", "A large naturally occurring community of plants and animals", "A type of ecosystem", "A geographic feature"], correctAnswer: "A large naturally occurring community of plants and animals" },
      { word: "Eutrophication", questionText: "What does 'eutrophication' mean?", options: ["Water purification", "Excessive nutrients in water causing harmful algae growth", "A type of drought", "Water erosion"], correctAnswer: "Excessive nutrients in water causing harmful algae growth" },
      { word: "Permafrost", questionText: "What does 'permafrost' mean?", options: ["Seasonal frozen ground", "Ground that remains frozen for two or more years", "A type of glacier", "Frozen precipitation"], correctAnswer: "Ground that remains frozen for two or more years" },
      { word: "Mitigation", questionText: "What does 'mitigation' (climate) mean?", options: ["Making climate change worse", "Actions taken to reduce the causes of climate change", "Adapting to climate change", "Measuring climate change"], correctAnswer: "Actions taken to reduce the causes of climate change" },
      { word: "Biodegradable", questionText: "What does 'biodegradable' mean?", options: ["Cannot be broken down naturally", "Able to be decomposed by bacteria or organisms", "A type of recycling", "A synthetic material"], correctAnswer: "Able to be decomposed by bacteria or organisms" },
      { word: "Habitat fragmentation", questionText: "What does 'habitat fragmentation' mean?", options: ["Creating new habitats", "Breaking up habitats into smaller isolated pieces", "Restoring natural habitats", "Expanding wildlife reserves"], correctAnswer: "Breaking up habitats into smaller isolated pieces" },
      { word: "Net zero", questionText: "What does 'net zero' mean?", options: ["Producing no energy", "Balancing carbon emissions with carbon removal", "Eliminating all industry", "A type of renewable energy"], correctAnswer: "Balancing carbon emissions with carbon removal" },
    ],
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ Connected to MongoDB");
    await VocabularyContent.deleteMany({});
    console.log("🗑️  Cleared existing vocabulary content");
    await VocabularyContent.insertMany(tasks);
    console.log(`✅ Seeded ${tasks.length} vocabulary tasks successfully!`);
    await mongoose.disconnect();
    console.log("✅ Done!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

seed();