import mongoose from "mongoose";
import dotenv from "dotenv";
import Question from "../models/Question.js";

dotenv.config();

const questions = [
  // ===========================
  // BEGINNER QUESTIONS (30)
  // ===========================
  {
    questionId: 1,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "What does 'Hello' mean?",
    options: [
      { id: "A", text: "Goodbye", isCorrect: false },
      { id: "B", text: "A greeting when you meet someone", isCorrect: true },
      { id: "C", text: "Thank you", isCorrect: false },
      { id: "D", text: "I don't know", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 2,
    category: "grammar",
    difficulty: "beginner",
    questionText: "Choose the correct sentence:",
    options: [
      { id: "A", text: "She go to school every day", isCorrect: false },
      { id: "B", text: "She goes to school every day", isCorrect: true },
      { id: "C", text: "She going to school every day", isCorrect: false },
      { id: "D", text: "She gone to school every day", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 3,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "What is the opposite of 'hot'?",
    options: [
      { id: "A", text: "Warm", isCorrect: false },
      { id: "B", text: "Cold", isCorrect: true },
      { id: "C", text: "Big", isCorrect: false },
      { id: "D", text: "Fast", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 4,
    category: "reading",
    difficulty: "beginner",
    questionText: "Read: 'The cat is sleeping on the sofa.' Where is the cat?",
    options: [
      { id: "A", text: "Under the sofa", isCorrect: false },
      { id: "B", text: "On the sofa", isCorrect: true },
      { id: "C", text: "Next to the sofa", isCorrect: false },
      { id: "D", text: "Behind the sofa", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 5,
    category: "grammar",
    difficulty: "beginner",
    questionText: "Complete: 'I ___ a student.'",
    options: [
      { id: "A", text: "am", isCorrect: true },
      { id: "B", text: "is", isCorrect: false },
      { id: "C", text: "are", isCorrect: false },
      { id: "D", text: "be", isCorrect: false },
    ],
    correctAnswer: "A",
    points: 1,
  },
  {
    questionId: 6,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "What does 'breakfast' mean?",
    options: [
      { id: "A", text: "The meal you eat in the morning", isCorrect: true },
      { id: "B", text: "The meal you eat at night", isCorrect: false },
      { id: "C", text: "A type of bread", isCorrect: false },
      { id: "D", text: "A break from work", isCorrect: false },
    ],
    correctAnswer: "A",
    points: 1,
  },
  {
    questionId: 7,
    category: "grammar",
    difficulty: "beginner",
    questionText: "Choose the correct form: 'We ___ friends.'",
    options: [
      { id: "A", text: "am", isCorrect: false },
      { id: "B", text: "is", isCorrect: false },
      { id: "C", text: "are", isCorrect: true },
      { id: "D", text: "be", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 8,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "What color is the sky on a clear day?",
    options: [
      { id: "A", text: "Green", isCorrect: false },
      { id: "B", text: "Blue", isCorrect: true },
      { id: "C", text: "Red", isCorrect: false },
      { id: "D", text: "Yellow", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 9,
    category: "reading",
    difficulty: "beginner",
    questionText: "'I like pizza.' What do I like?",
    options: [
      { id: "A", text: "Burger", isCorrect: false },
      { id: "B", text: "Pizza", isCorrect: true },
      { id: "C", text: "Pasta", isCorrect: false },
      { id: "D", text: "Salad", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 10,
    category: "grammar",
    difficulty: "beginner",
    questionText: "What is the plural of 'book'?",
    options: [
      { id: "A", text: "book", isCorrect: false },
      { id: "B", text: "books", isCorrect: true },
      { id: "C", text: "bookes", isCorrect: false },
      { id: "D", text: "bookies", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 11,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "What is the opposite of 'big'?",
    options: [
      { id: "A", text: "Tall", isCorrect: false },
      { id: "B", text: "Heavy", isCorrect: false },
      { id: "C", text: "Small", isCorrect: true },
      { id: "D", text: "Long", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 12,
    category: "grammar",
    difficulty: "beginner",
    questionText: "Choose the correct sentence:",
    options: [
      { id: "A", text: "He have a dog", isCorrect: false },
      { id: "B", text: "He has a dog", isCorrect: true },
      { id: "C", text: "He haves a dog", isCorrect: false },
      { id: "D", text: "He having a dog", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 13,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "What does 'tired' mean?",
    options: [
      { id: "A", text: "Feeling happy", isCorrect: false },
      { id: "B", text: "Needing sleep or rest", isCorrect: true },
      { id: "C", text: "Feeling hungry", isCorrect: false },
      { id: "D", text: "Feeling angry", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 14,
    category: "reading",
    difficulty: "beginner",
    questionText: "'Tom has two brothers.' How many brothers does Tom have?",
    options: [
      { id: "A", text: "One", isCorrect: false },
      { id: "B", text: "Three", isCorrect: false },
      { id: "C", text: "Two", isCorrect: true },
      { id: "D", text: "Four", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 15,
    category: "grammar",
    difficulty: "beginner",
    questionText: "Which word is a verb?",
    options: [
      { id: "A", text: "Happy", isCorrect: false },
      { id: "B", text: "Apple", isCorrect: false },
      { id: "C", text: "Run", isCorrect: true },
      { id: "D", text: "Blue", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 16,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "What does 'happy' mean?",
    options: [
      { id: "A", text: "Feeling sad", isCorrect: false },
      { id: "B", text: "Feeling angry", isCorrect: false },
      { id: "C", text: "Feeling good or pleased", isCorrect: true },
      { id: "D", text: "Feeling scared", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 17,
    category: "grammar",
    difficulty: "beginner",
    questionText: "Complete: 'She ___ to music every day.'",
    options: [
      { id: "A", text: "listen", isCorrect: false },
      { id: "B", text: "listens", isCorrect: true },
      { id: "C", text: "listening", isCorrect: false },
      { id: "D", text: "listened", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 18,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "Which animal says 'meow'?",
    options: [
      { id: "A", text: "Dog", isCorrect: false },
      { id: "B", text: "Cat", isCorrect: true },
      { id: "C", text: "Bird", isCorrect: false },
      { id: "D", text: "Fish", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 19,
    category: "grammar",
    difficulty: "beginner",
    questionText: "What is the plural of 'child'?",
    options: [
      { id: "A", text: "childs", isCorrect: false },
      { id: "B", text: "childes", isCorrect: false },
      { id: "C", text: "children", isCorrect: true },
      { id: "D", text: "child's", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 20,
    category: "reading",
    difficulty: "beginner",
    questionText: "'Anna wakes up at 7 AM.' What time does Anna wake up?",
    options: [
      { id: "A", text: "6 AM", isCorrect: false },
      { id: "B", text: "8 AM", isCorrect: false },
      { id: "C", text: "7 AM", isCorrect: true },
      { id: "D", text: "9 AM", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 21,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "What is a 'pencil' used for?",
    options: [
      { id: "A", text: "Eating", isCorrect: false },
      { id: "B", text: "Writing or drawing", isCorrect: true },
      { id: "C", text: "Cutting", isCorrect: false },
      { id: "D", text: "Drinking", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 22,
    category: "grammar",
    difficulty: "beginner",
    questionText: "Which is a question word?",
    options: [
      { id: "A", text: "And", isCorrect: false },
      { id: "B", text: "But", isCorrect: false },
      { id: "C", text: "Where", isCorrect: true },
      { id: "D", text: "The", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 23,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "What does 'drink' mean?",
    options: [
      { id: "A", text: "To eat something solid", isCorrect: false },
      { id: "B", text: "To swallow a liquid", isCorrect: true },
      { id: "C", text: "To sleep", isCorrect: false },
      { id: "D", text: "To run fast", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 24,
    category: "grammar",
    difficulty: "beginner",
    questionText: "Choose the correct article: '___ apple a day keeps the doctor away.'",
    options: [
      { id: "A", text: "A", isCorrect: false },
      { id: "B", text: "The", isCorrect: false },
      { id: "C", text: "An", isCorrect: true },
      { id: "D", text: "Some", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 25,
    category: "reading",
    difficulty: "beginner",
    questionText: "'The shop is closed on Sundays.' When is the shop closed?",
    options: [
      { id: "A", text: "Mondays", isCorrect: false },
      { id: "B", text: "Saturdays", isCorrect: false },
      { id: "C", text: "Sundays", isCorrect: true },
      { id: "D", text: "Fridays", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 26,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "What is the opposite of 'day'?",
    options: [
      { id: "A", text: "Morning", isCorrect: false },
      { id: "B", text: "Evening", isCorrect: false },
      { id: "C", text: "Night", isCorrect: true },
      { id: "D", text: "Afternoon", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 27,
    category: "grammar",
    difficulty: "beginner",
    questionText: "Complete: 'They ___ playing football now.'",
    options: [
      { id: "A", text: "is", isCorrect: false },
      { id: "B", text: "are", isCorrect: true },
      { id: "C", text: "am", isCorrect: false },
      { id: "D", text: "was", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 28,
    category: "vocabulary",
    difficulty: "beginner",
    questionText: "How many days are in a week?",
    options: [
      { id: "A", text: "Five", isCorrect: false },
      { id: "B", text: "Six", isCorrect: false },
      { id: "C", text: "Seven", isCorrect: true },
      { id: "D", text: "Eight", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 29,
    category: "grammar",
    difficulty: "beginner",
    questionText: "Which sentence uses 'this' correctly?",
    options: [
      { id: "A", text: "This are my keys", isCorrect: false },
      { id: "B", text: "This is my key", isCorrect: true },
      { id: "C", text: "This am my key", isCorrect: false },
      { id: "D", text: "This be my key", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 30,
    category: "reading",
    difficulty: "beginner",
    questionText: "'My favourite colour is green.' What is the person's favourite colour?",
    options: [
      { id: "A", text: "Blue", isCorrect: false },
      { id: "B", text: "Red", isCorrect: false },
      { id: "C", text: "Green", isCorrect: true },
      { id: "D", text: "Yellow", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },

  // ==============================
  // INTERMEDIATE QUESTIONS (30)
  // ==============================
  {
    questionId: 31,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "Complete: 'Right now, they ___ watching TV.'",
    options: [
      { id: "A", text: "is", isCorrect: false },
      { id: "B", text: "am", isCorrect: false },
      { id: "C", text: "are", isCorrect: true },
      { id: "D", text: "was", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 32,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "Which sentence is correct?",
    options: [
      { id: "A", text: "You must to study hard", isCorrect: false },
      { id: "B", text: "You must studying hard", isCorrect: false },
      { id: "C", text: "You must study hard", isCorrect: true },
      { id: "D", text: "You must studies hard", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 33,
    category: "vocabulary",
    difficulty: "intermediate",
    questionText: "'She felt exhausted after running.' What does 'exhausted' mean?",
    options: [
      { id: "A", text: "Happy", isCorrect: false },
      { id: "B", text: "Excited", isCorrect: false },
      { id: "C", text: "Very tired", isCorrect: true },
      { id: "D", text: "Hungry", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 34,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "Yesterday, I ___ to the park.",
    options: [
      { id: "A", text: "go", isCorrect: false },
      { id: "B", text: "goes", isCorrect: false },
      { id: "C", text: "went", isCorrect: true },
      { id: "D", text: "going", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 35,
    category: "vocabulary",
    difficulty: "intermediate",
    questionText: "What does 'purchase' mean?",
    options: [
      { id: "A", text: "To sell", isCorrect: false },
      { id: "B", text: "To buy", isCorrect: true },
      { id: "C", text: "To give", isCorrect: false },
      { id: "D", text: "To borrow", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 36,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "She has ___ to Paris twice.",
    options: [
      { id: "A", text: "go", isCorrect: false },
      { id: "B", text: "went", isCorrect: false },
      { id: "C", text: "been", isCorrect: true },
      { id: "D", text: "going", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 37,
    category: "reading",
    difficulty: "intermediate",
    questionText: "'Despite the rain, we enjoyed the picnic.' What does this mean?",
    options: [
      { id: "A", text: "We didn't go because of rain", isCorrect: false },
      { id: "B", text: "We enjoyed the picnic even though it rained", isCorrect: true },
      { id: "C", text: "The rain stopped before the picnic", isCorrect: false },
      { id: "D", text: "We didn't enjoy the picnic", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 38,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "If I ___ you, I would apologize.",
    options: [
      { id: "A", text: "am", isCorrect: false },
      { id: "B", text: "was", isCorrect: false },
      { id: "C", text: "were", isCorrect: true },
      { id: "D", text: "be", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 39,
    category: "vocabulary",
    difficulty: "intermediate",
    questionText: "What does 'abandon' mean?",
    options: [
      { id: "A", text: "To keep", isCorrect: false },
      { id: "B", text: "To leave behind", isCorrect: true },
      { id: "C", text: "To find", isCorrect: false },
      { id: "D", text: "To protect", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 40,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "The book ___ by millions of people.",
    options: [
      { id: "A", text: "read", isCorrect: false },
      { id: "B", text: "reads", isCorrect: false },
      { id: "C", text: "was read", isCorrect: true },
      { id: "D", text: "reading", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 41,
    category: "vocabulary",
    difficulty: "intermediate",
    questionText: "What does 'curious' mean?",
    options: [
      { id: "A", text: "Bored and uninterested", isCorrect: false },
      { id: "B", text: "Eager to know or learn something", isCorrect: true },
      { id: "C", text: "Feeling scared", isCorrect: false },
      { id: "D", text: "Feeling sleepy", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 42,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "She ___ her homework before dinner.",
    options: [
      { id: "A", text: "finish", isCorrect: false },
      { id: "B", text: "finishes", isCorrect: false },
      { id: "C", text: "finished", isCorrect: true },
      { id: "D", text: "finishing", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 43,
    category: "reading",
    difficulty: "intermediate",
    questionText: "'The more you practice, the better you become.' What is the main idea?",
    options: [
      { id: "A", text: "Practice is boring", isCorrect: false },
      { id: "B", text: "Regular practice leads to improvement", isCorrect: true },
      { id: "C", text: "You don't need to practice", isCorrect: false },
      { id: "D", text: "Better people practice more", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 44,
    category: "vocabulary",
    difficulty: "intermediate",
    questionText: "What does 'generous' mean?",
    options: [
      { id: "A", text: "Selfish and greedy", isCorrect: false },
      { id: "B", text: "Willing to give freely", isCorrect: true },
      { id: "C", text: "Very angry", isCorrect: false },
      { id: "D", text: "Extremely shy", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 45,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "They ___ in this company for five years.",
    options: [
      { id: "A", text: "work", isCorrect: false },
      { id: "B", text: "worked", isCorrect: false },
      { id: "C", text: "have worked", isCorrect: true },
      { id: "D", text: "are working", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 46,
    category: "vocabulary",
    difficulty: "intermediate",
    questionText: "What does 'ancient' mean?",
    options: [
      { id: "A", text: "Very new", isCorrect: false },
      { id: "B", text: "Very old", isCorrect: true },
      { id: "C", text: "Very large", isCorrect: false },
      { id: "D", text: "Very small", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 47,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "You ___ wear a seatbelt in a car. It's the law.",
    options: [
      { id: "A", text: "should", isCorrect: false },
      { id: "B", text: "might", isCorrect: false },
      { id: "C", text: "must", isCorrect: true },
      { id: "D", text: "could", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 48,
    category: "reading",
    difficulty: "intermediate",
    questionText: "'She spoke so quietly that nobody heard her.' Why didn't anyone hear her?",
    options: [
      { id: "A", text: "She did not say anything", isCorrect: false },
      { id: "B", text: "She spoke too softly", isCorrect: true },
      { id: "C", text: "Everyone was sleeping", isCorrect: false },
      { id: "D", text: "She spoke a foreign language", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 49,
    category: "vocabulary",
    difficulty: "intermediate",
    questionText: "What does 'nervous' mean?",
    options: [
      { id: "A", text: "Feeling calm and relaxed", isCorrect: false },
      { id: "B", text: "Feeling worried or anxious", isCorrect: true },
      { id: "C", text: "Feeling very happy", isCorrect: false },
      { id: "D", text: "Feeling bored", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 50,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "He asked me where ___ from.",
    options: [
      { id: "A", text: "do I come", isCorrect: false },
      { id: "B", text: "I come", isCorrect: true },
      { id: "C", text: "I came", isCorrect: false },
      { id: "D", text: "did I come", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 51,
    category: "vocabulary",
    difficulty: "intermediate",
    questionText: "What does 'enormous' mean?",
    options: [
      { id: "A", text: "Very small", isCorrect: false },
      { id: "B", text: "Very fast", isCorrect: false },
      { id: "C", text: "Very large", isCorrect: true },
      { id: "D", text: "Very loud", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 52,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "By the time he arrived, the movie ___.",
    options: [
      { id: "A", text: "already started", isCorrect: false },
      { id: "B", text: "has already started", isCorrect: false },
      { id: "C", text: "had already started", isCorrect: true },
      { id: "D", text: "already starts", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 53,
    category: "reading",
    difficulty: "intermediate",
    questionText: "'Although he was tired, he continued working.' What does this tell us about him?",
    options: [
      { id: "A", text: "He stopped working because he was tired", isCorrect: false },
      { id: "B", text: "He kept working in spite of his tiredness", isCorrect: true },
      { id: "C", text: "He was not tired at all", isCorrect: false },
      { id: "D", text: "He went to sleep", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 54,
    category: "vocabulary",
    difficulty: "intermediate",
    questionText: "What does 'reliable' mean?",
    options: [
      { id: "A", text: "Often late or unpredictable", isCorrect: false },
      { id: "B", text: "Consistently good and trustworthy", isCorrect: true },
      { id: "C", text: "Very expensive", isCorrect: false },
      { id: "D", text: "Difficult to understand", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 55,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "I don't enjoy ___ in the rain.",
    options: [
      { id: "A", text: "to walk", isCorrect: false },
      { id: "B", text: "walk", isCorrect: false },
      { id: "C", text: "walking", isCorrect: true },
      { id: "D", text: "walked", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 56,
    category: "vocabulary",
    difficulty: "intermediate",
    questionText: "What does 'opponent' mean?",
    options: [
      { id: "A", text: "A close friend", isCorrect: false },
      { id: "B", text: "A team member", isCorrect: false },
      { id: "C", text: "A person who competes against you", isCorrect: true },
      { id: "D", text: "A teacher or mentor", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 57,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "She suggested ___ to the beach.",
    options: [
      { id: "A", text: "to go", isCorrect: false },
      { id: "B", text: "go", isCorrect: false },
      { id: "C", text: "going", isCorrect: true },
      { id: "D", text: "gone", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 58,
    category: "reading",
    difficulty: "intermediate",
    questionText: "'The exam was harder than expected, but most students passed.' What can we conclude?",
    options: [
      { id: "A", text: "Nobody passed the exam", isCorrect: false },
      { id: "B", text: "Most students failed because it was hard", isCorrect: false },
      { id: "C", text: "Most students passed despite the difficulty", isCorrect: true },
      { id: "D", text: "The exam was easy", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 59,
    category: "vocabulary",
    difficulty: "intermediate",
    questionText: "What does 'prevent' mean?",
    options: [
      { id: "A", text: "To allow something to happen", isCorrect: false },
      { id: "B", text: "To stop something from happening", isCorrect: true },
      { id: "C", text: "To repeat something", isCorrect: false },
      { id: "D", text: "To explain something", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 60,
    category: "grammar",
    difficulty: "intermediate",
    questionText: "The letter ___ two days ago.",
    options: [
      { id: "A", text: "send", isCorrect: false },
      { id: "B", text: "sends", isCorrect: false },
      { id: "C", text: "was sent", isCorrect: true },
      { id: "D", text: "sent", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },

  // =========================
  // ADVANCED QUESTIONS (30)
  // =========================
  {
    questionId: 61,
    category: "grammar",
    difficulty: "advanced",
    questionText: "Choose the correct sentence:",
    options: [
      { id: "A", text: "When I arrived, they already left", isCorrect: false },
      { id: "B", text: "When I arrived, they have already left", isCorrect: false },
      { id: "C", text: "When I arrived, they had already left", isCorrect: true },
      { id: "D", text: "When I arrived, they already leave", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 62,
    category: "grammar",
    difficulty: "advanced",
    questionText: "Which conditional sentence is correct?",
    options: [
      { id: "A", text: "If I will see him, I will tell him", isCorrect: false },
      { id: "B", text: "If I see him, I will tell him", isCorrect: true },
      { id: "C", text: "If I saw him, I will tell him", isCorrect: false },
      { id: "D", text: "If I seen him, I will tell him", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 63,
    category: "idioms",
    difficulty: "advanced",
    questionText: "'It's raining cats and dogs.' What does this mean?",
    options: [
      { id: "A", text: "Animals are falling", isCorrect: false },
      { id: "B", text: "It's raining very heavily", isCorrect: true },
      { id: "C", text: "The weather is nice", isCorrect: false },
      { id: "D", text: "There are animals outside", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 64,
    category: "grammar",
    difficulty: "advanced",
    questionText: "By next year, she ___ her degree.",
    options: [
      { id: "A", text: "completes", isCorrect: false },
      { id: "B", text: "will complete", isCorrect: false },
      { id: "C", text: "will have completed", isCorrect: true },
      { id: "D", text: "completed", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 65,
    category: "vocabulary",
    difficulty: "advanced",
    questionText: "What does 'meticulous' mean?",
    options: [
      { id: "A", text: "Careless", isCorrect: false },
      { id: "B", text: "Very careful and precise", isCorrect: true },
      { id: "C", text: "Fast", isCorrect: false },
      { id: "D", text: "Lazy", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 66,
    category: "grammar",
    difficulty: "advanced",
    questionText: "The report ___ before the meeting starts.",
    options: [
      { id: "A", text: "must finish", isCorrect: false },
      { id: "B", text: "must be finished", isCorrect: true },
      { id: "C", text: "must finishing", isCorrect: false },
      { id: "D", text: "must to finish", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 67,
    category: "idioms",
    difficulty: "advanced",
    questionText: "'Break the ice' means:",
    options: [
      { id: "A", text: "To make people feel more relaxed", isCorrect: true },
      { id: "B", text: "To break something frozen", isCorrect: false },
      { id: "C", text: "To start a fight", isCorrect: false },
      { id: "D", text: "To leave early", isCorrect: false },
    ],
    correctAnswer: "A",
    points: 1,
  },
  {
    questionId: 68,
    category: "grammar",
    difficulty: "advanced",
    questionText: "I wish I ___ more time yesterday.",
    options: [
      { id: "A", text: "have", isCorrect: false },
      { id: "B", text: "had", isCorrect: false },
      { id: "C", text: "had had", isCorrect: true },
      { id: "D", text: "have had", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 69,
    category: "vocabulary",
    difficulty: "advanced",
    questionText: "What does 'eloquent' mean?",
    options: [
      { id: "A", text: "Unable to speak", isCorrect: false },
      { id: "B", text: "Speaking fluently and persuasively", isCorrect: true },
      { id: "C", text: "Very quiet", isCorrect: false },
      { id: "D", text: "Confusing", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 70,
    category: "grammar",
    difficulty: "advanced",
    questionText: "Hardly ___ the door when the phone rang.",
    options: [
      { id: "A", text: "I opened", isCorrect: false },
      { id: "B", text: "had I opened", isCorrect: true },
      { id: "C", text: "I had opened", isCorrect: false },
      { id: "D", text: "did I open", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 71,
    category: "vocabulary",
    difficulty: "advanced",
    questionText: "What does 'ambiguous' mean?",
    options: [
      { id: "A", text: "Very clear and obvious", isCorrect: false },
      { id: "B", text: "Open to more than one interpretation", isCorrect: true },
      { id: "C", text: "Extremely confident", isCorrect: false },
      { id: "D", text: "Rarely seen", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 72,
    category: "grammar",
    difficulty: "advanced",
    questionText: "Not only ___ late, but he also forgot his report.",
    options: [
      { id: "A", text: "he was", isCorrect: false },
      { id: "B", text: "was he", isCorrect: true },
      { id: "C", text: "he is", isCorrect: false },
      { id: "D", text: "is he", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 73,
    category: "idioms",
    difficulty: "advanced",
    questionText: "'Bite the bullet' means:",
    options: [
      { id: "A", text: "To eat something dangerous", isCorrect: false },
      { id: "B", text: "To endure a painful situation with courage", isCorrect: true },
      { id: "C", text: "To give up on a task", isCorrect: false },
      { id: "D", text: "To speak harshly to someone", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 74,
    category: "grammar",
    difficulty: "advanced",
    questionText: "The manager ___ that all employees attend the training.",
    options: [
      { id: "A", text: "insisted", isCorrect: false },
      { id: "B", text: "insisted that", isCorrect: false },
      { id: "C", text: "insisted that all employees attended", isCorrect: false },
      { id: "D", text: "insisted that all employees attend", isCorrect: true },
    ],
    correctAnswer: "D",
    points: 1,
  },
  {
    questionId: 75,
    category: "vocabulary",
    difficulty: "advanced",
    questionText: "What does 'pragmatic' mean?",
    options: [
      { id: "A", text: "Idealistic and unrealistic", isCorrect: false },
      { id: "B", text: "Dealing with things sensibly and practically", isCorrect: true },
      { id: "C", text: "Overly emotional", isCorrect: false },
      { id: "D", text: "Strictly following rules", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 76,
    category: "reading",
    difficulty: "advanced",
    questionText: "'The policy was implemented despite widespread opposition.' What does this imply?",
    options: [
      { id: "A", text: "The policy was canceled due to opposition", isCorrect: false },
      { id: "B", text: "The policy was put in place even though many people were against it", isCorrect: true },
      { id: "C", text: "The policy had full public support", isCorrect: false },
      { id: "D", text: "Opposition forced changes to the policy", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 77,
    category: "grammar",
    difficulty: "advanced",
    questionText: "___ he studied hard, he failed the exam.",
    options: [
      { id: "A", text: "Because", isCorrect: false },
      { id: "B", text: "Even though", isCorrect: true },
      { id: "C", text: "So that", isCorrect: false },
      { id: "D", text: "As long as", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 78,
    category: "vocabulary",
    difficulty: "advanced",
    questionText: "What does 'incoherent' mean?",
    options: [
      { id: "A", text: "Clear and easy to understand", isCorrect: false },
      { id: "B", text: "Expressed in a way that is difficult to understand", isCorrect: true },
      { id: "C", text: "Extremely intelligent", isCorrect: false },
      { id: "D", text: "Formal and polite", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 79,
    category: "idioms",
    difficulty: "advanced",
    questionText: "'Hit the nail on the head' means:",
    options: [
      { id: "A", text: "To hammer something correctly", isCorrect: false },
      { id: "B", text: "To describe exactly what is causing a problem", isCorrect: true },
      { id: "C", text: "To be aggressive", isCorrect: false },
      { id: "D", text: "To miss an opportunity", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 80,
    category: "grammar",
    difficulty: "advanced",
    questionText: "He denied ___ the document.",
    options: [
      { id: "A", text: "to steal", isCorrect: false },
      { id: "B", text: "steal", isCorrect: false },
      { id: "C", text: "stealing", isCorrect: true },
      { id: "D", text: "stolen", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 81,
    category: "vocabulary",
    difficulty: "advanced",
    questionText: "What does 'diligent' mean?",
    options: [
      { id: "A", text: "Lazy and unmotivated", isCorrect: false },
      { id: "B", text: "Showing careful and persistent effort", isCorrect: true },
      { id: "C", text: "Reckless and careless", isCorrect: false },
      { id: "D", text: "Very cheerful", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 82,
    category: "grammar",
    difficulty: "advanced",
    questionText: "Had I known about the problem, I ___ earlier.",
    options: [
      { id: "A", text: "would help", isCorrect: false },
      { id: "B", text: "will have helped", isCorrect: false },
      { id: "C", text: "would have helped", isCorrect: true },
      { id: "D", text: "had helped", isCorrect: false },
    ],
    correctAnswer: "C",
    points: 1,
  },
  {
    questionId: 83,
    category: "reading",
    difficulty: "advanced",
    questionText: "'His argument, though compelling, lacked empirical evidence.' What is the writer's point?",
    options: [
      { id: "A", text: "The argument was weak and unpersuasive", isCorrect: false },
      { id: "B", text: "The argument was persuasive but not backed by data or facts", isCorrect: true },
      { id: "C", text: "The argument was fully supported by evidence", isCorrect: false },
      { id: "D", text: "The argument was too complex to understand", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 84,
    category: "vocabulary",
    difficulty: "advanced",
    questionText: "What does 'ubiquitous' mean?",
    options: [
      { id: "A", text: "Extremely rare", isCorrect: false },
      { id: "B", text: "Present or appearing everywhere", isCorrect: true },
      { id: "C", text: "Extremely dangerous", isCorrect: false },
      { id: "D", text: "Highly valuable", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 85,
    category: "grammar",
    difficulty: "advanced",
    questionText: "So complex ___ that few people could understand it.",
    options: [
      { id: "A", text: "the theory was", isCorrect: false },
      { id: "B", text: "was the theory", isCorrect: true },
      { id: "C", text: "the theory is", isCorrect: false },
      { id: "D", text: "is the theory", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 86,
    category: "idioms",
    difficulty: "advanced",
    questionText: "'The ball is in your court' means:",
    options: [
      { id: "A", text: "You are playing tennis", isCorrect: false },
      { id: "B", text: "It is now your responsibility to take action", isCorrect: true },
      { id: "C", text: "You have made a mistake", isCorrect: false },
      { id: "D", text: "Someone is asking for your opinion", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 87,
    category: "vocabulary",
    difficulty: "advanced",
    questionText: "What does 'exacerbate' mean?",
    options: [
      { id: "A", text: "To improve a situation", isCorrect: false },
      { id: "B", text: "To make a problem worse", isCorrect: true },
      { id: "C", text: "To solve a conflict", isCorrect: false },
      { id: "D", text: "To ignore a problem", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 88,
    category: "grammar",
    difficulty: "advanced",
    questionText: "The scientist's findings ___ further investigation.",
    options: [
      { id: "A", text: "warrant", isCorrect: true },
      { id: "B", text: "warrants", isCorrect: false },
      { id: "C", text: "warranting", isCorrect: false },
      { id: "D", text: "warranted to", isCorrect: false },
    ],
    correctAnswer: "A",
    points: 1,
  },
  {
    questionId: 89,
    category: "reading",
    difficulty: "advanced",
    questionText: "'The author implies rather than states the character's guilt.' What writing technique is described?",
    options: [
      { id: "A", text: "Foreshadowing", isCorrect: false },
      { id: "B", text: "Implication and subtext", isCorrect: true },
      { id: "C", text: "Direct characterization", isCorrect: false },
      { id: "D", text: "Stream of consciousness", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
  {
    questionId: 90,
    category: "vocabulary",
    difficulty: "advanced",
    questionText: "What does 'paradox' mean?",
    options: [
      { id: "A", text: "A simple and obvious statement", isCorrect: false },
      { id: "B", text: "A statement that seems contradictory but may be true", isCorrect: true },
      { id: "C", text: "An example used to explain something", isCorrect: false },
      { id: "D", text: "A common misunderstanding", isCorrect: false },
    ],
    correctAnswer: "B",
    points: 1,
  },
];

const seedQuestions = async () => {
  try {
    console.log("🔌 Connecting to MongoDB...");
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB Connected\n");

    console.log("🗑️  Clearing existing questions...");
    await Question.deleteMany({});
    console.log("✅ Cleared\n");

    console.log("📝 Inserting 90 questions...");
    await Question.insertMany(questions);
    console.log("✅ Inserted\n");

    const beginnerCount = questions.filter(q => q.difficulty === 'beginner').length;
    const intermediateCount = questions.filter(q => q.difficulty === 'intermediate').length;
    const advancedCount = questions.filter(q => q.difficulty === 'advanced').length;

    console.log("📊 Summary:");
    console.log(`   🟢 Beginner:     ${beginnerCount}`);
    console.log(`   🟡 Intermediate: ${intermediateCount}`);
    console.log(`   🔴 Advanced:     ${advancedCount}`);
    console.log(`   📚 Total:        ${questions.length}\n`);

    console.log("✅ Seed completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
};

seedQuestions();